// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: bash_history.proto

package snipspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BashHistoryService_GetCommand_FullMethodName      = "/notx.v1.BashHistoryService/GetCommand"
	BashHistoryService_ListCommands_FullMethodName    = "/notx.v1.BashHistoryService/ListCommands"
	BashHistoryService_SearchCommands_FullMethodName  = "/notx.v1.BashHistoryService/SearchCommands"
	BashHistoryService_GetVariations_FullMethodName   = "/notx.v1.BashHistoryService/GetVariations"
	BashHistoryService_GetStats_FullMethodName        = "/notx.v1.BashHistoryService/GetStats"
	BashHistoryService_AnnotateCommand_FullMethodName = "/notx.v1.BashHistoryService/AnnotateCommand"
	BashHistoryService_TriggerSync_FullMethodName     = "/notx.v1.BashHistoryService/TriggerSync"
)

// BashHistoryServiceClient is the client API for BashHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BashHistoryServiceClient interface {
	GetCommand(ctx context.Context, in *GetCommandRequest, opts ...grpc.CallOption) (*GetCommandResponse, error)
	ListCommands(ctx context.Context, in *ListCommandsRequest, opts ...grpc.CallOption) (*ListCommandsResponse, error)
	SearchCommands(ctx context.Context, in *SearchCommandsRequest, opts ...grpc.CallOption) (*SearchCommandsResponse, error)
	GetVariations(ctx context.Context, in *GetVariationsRequest, opts ...grpc.CallOption) (*GetVariationsResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	AnnotateCommand(ctx context.Context, in *AnnotateCommandRequest, opts ...grpc.CallOption) (*AnnotateCommandResponse, error)
	TriggerSync(ctx context.Context, in *TriggerSyncRequest, opts ...grpc.CallOption) (*TriggerSyncResponse, error)
}

type bashHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBashHistoryServiceClient(cc grpc.ClientConnInterface) BashHistoryServiceClient {
	return &bashHistoryServiceClient{cc}
}

func (c *bashHistoryServiceClient) GetCommand(ctx context.Context, in *GetCommandRequest, opts ...grpc.CallOption) (*GetCommandResponse, error) {
	out := new(GetCommandResponse)
	err := c.cc.Invoke(ctx, BashHistoryService_GetCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bashHistoryServiceClient) ListCommands(ctx context.Context, in *ListCommandsRequest, opts ...grpc.CallOption) (*ListCommandsResponse, error) {
	out := new(ListCommandsResponse)
	err := c.cc.Invoke(ctx, BashHistoryService_ListCommands_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bashHistoryServiceClient) SearchCommands(ctx context.Context, in *SearchCommandsRequest, opts ...grpc.CallOption) (*SearchCommandsResponse, error) {
	out := new(SearchCommandsResponse)
	err := c.cc.Invoke(ctx, BashHistoryService_SearchCommands_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bashHistoryServiceClient) GetVariations(ctx context.Context, in *GetVariationsRequest, opts ...grpc.CallOption) (*GetVariationsResponse, error) {
	out := new(GetVariationsResponse)
	err := c.cc.Invoke(ctx, BashHistoryService_GetVariations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bashHistoryServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, BashHistoryService_GetStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bashHistoryServiceClient) AnnotateCommand(ctx context.Context, in *AnnotateCommandRequest, opts ...grpc.CallOption) (*AnnotateCommandResponse, error) {
	out := new(AnnotateCommandResponse)
	err := c.cc.Invoke(ctx, BashHistoryService_AnnotateCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bashHistoryServiceClient) TriggerSync(ctx context.Context, in *TriggerSyncRequest, opts ...grpc.CallOption) (*TriggerSyncResponse, error) {
	out := new(TriggerSyncResponse)
	err := c.cc.Invoke(ctx, BashHistoryService_TriggerSync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BashHistoryServiceServer is the server API for BashHistoryService service.
// All implementations must embed UnimplementedBashHistoryServiceServer
// for forward compatibility
type BashHistoryServiceServer interface {
	GetCommand(context.Context, *GetCommandRequest) (*GetCommandResponse, error)
	ListCommands(context.Context, *ListCommandsRequest) (*ListCommandsResponse, error)
	SearchCommands(context.Context, *SearchCommandsRequest) (*SearchCommandsResponse, error)
	GetVariations(context.Context, *GetVariationsRequest) (*GetVariationsResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	AnnotateCommand(context.Context, *AnnotateCommandRequest) (*AnnotateCommandResponse, error)
	TriggerSync(context.Context, *TriggerSyncRequest) (*TriggerSyncResponse, error)
	mustEmbedUnimplementedBashHistoryServiceServer()
}

// UnimplementedBashHistoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBashHistoryServiceServer struct {
}

func (UnimplementedBashHistoryServiceServer) GetCommand(context.Context, *GetCommandRequest) (*GetCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommand not implemented")
}
func (UnimplementedBashHistoryServiceServer) ListCommands(context.Context, *ListCommandsRequest) (*ListCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCommands not implemented")
}
func (UnimplementedBashHistoryServiceServer) SearchCommands(context.Context, *SearchCommandsRequest) (*SearchCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCommands not implemented")
}
func (UnimplementedBashHistoryServiceServer) GetVariations(context.Context, *GetVariationsRequest) (*GetVariationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVariations not implemented")
}
func (UnimplementedBashHistoryServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedBashHistoryServiceServer) AnnotateCommand(context.Context, *AnnotateCommandRequest) (*AnnotateCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnnotateCommand not implemented")
}
func (UnimplementedBashHistoryServiceServer) TriggerSync(context.Context, *TriggerSyncRequest) (*TriggerSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerSync not implemented")
}
func (UnimplementedBashHistoryServiceServer) mustEmbedUnimplementedBashHistoryServiceServer() {}

// UnsafeBashHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BashHistoryServiceServer will
// result in compilation errors.
type UnsafeBashHistoryServiceServer interface {
	mustEmbedUnimplementedBashHistoryServiceServer()
}

func RegisterBashHistoryServiceServer(s grpc.ServiceRegistrar, srv BashHistoryServiceServer) {
	s.RegisterService(&BashHistoryService_ServiceDesc, srv)
}

func _BashHistoryService_GetCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BashHistoryServiceServer).GetCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BashHistoryService_GetCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BashHistoryServiceServer).GetCommand(ctx, req.(*GetCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BashHistoryService_ListCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BashHistoryServiceServer).ListCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BashHistoryService_ListCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BashHistoryServiceServer).ListCommands(ctx, req.(*ListCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BashHistoryService_SearchCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BashHistoryServiceServer).SearchCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BashHistoryService_SearchCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BashHistoryServiceServer).SearchCommands(ctx, req.(*SearchCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BashHistoryService_GetVariations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVariationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BashHistoryServiceServer).GetVariations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BashHistoryService_GetVariations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BashHistoryServiceServer).GetVariations(ctx, req.(*GetVariationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BashHistoryService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BashHistoryServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BashHistoryService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BashHistoryServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BashHistoryService_AnnotateCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnotateCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BashHistoryServiceServer).AnnotateCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BashHistoryService_AnnotateCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BashHistoryServiceServer).AnnotateCommand(ctx, req.(*AnnotateCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BashHistoryService_TriggerSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BashHistoryServiceServer).TriggerSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BashHistoryService_TriggerSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BashHistoryServiceServer).TriggerSync(ctx, req.(*TriggerSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BashHistoryService_ServiceDesc is the grpc.ServiceDesc for BashHistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BashHistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notx.v1.BashHistoryService",
	HandlerType: (*BashHistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCommand",
			Handler:    _BashHistoryService_GetCommand_Handler,
		},
		{
			MethodName: "ListCommands",
			Handler:    _BashHistoryService_ListCommands_Handler,
		},
		{
			MethodName: "SearchCommands",
			Handler:    _BashHistoryService_SearchCommands_Handler,
		},
		{
			MethodName: "GetVariations",
			Handler:    _BashHistoryService_GetVariations_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _BashHistoryService_GetStats_Handler,
		},
		{
			MethodName: "AnnotateCommand",
			Handler:    _BashHistoryService_AnnotateCommand_Handler,
		},
		{
			MethodName: "TriggerSync",
			Handler:    _BashHistoryService_TriggerSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bash_history.proto",
}
