// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: notx.proto

package notxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NoteService_GetNote_FullMethodName         = "/notx.v1.NoteService/GetNote"
	NoteService_ListNotes_FullMethodName       = "/notx.v1.NoteService/ListNotes"
	NoteService_CreateNote_FullMethodName      = "/notx.v1.NoteService/CreateNote"
	NoteService_DeleteNote_FullMethodName      = "/notx.v1.NoteService/DeleteNote"
	NoteService_AppendEvent_FullMethodName     = "/notx.v1.NoteService/AppendEvent"
	NoteService_StreamEvents_FullMethodName    = "/notx.v1.NoteService/StreamEvents"
	NoteService_SearchNotes_FullMethodName     = "/notx.v1.NoteService/SearchNotes"
	NoteService_ShareSecureNote_FullMethodName = "/notx.v1.NoteService/ShareSecureNote"
)

// NoteServiceClient is the client API for NoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoteServiceClient interface {
	// GetNote returns the full header + all events for a note.
	GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error)
	// ListNotes returns all note headers visible to the caller.
	ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error)
	// CreateNote registers a new note (header only; events follow via AppendEvent).
	CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error)
	// DeleteNote soft-deletes a note by URN.
	DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error)
	// AppendEvent appends a single event to an existing note.
	// For normal notes the server stores the plaintext entries and advances the
	// index. For secure notes it stores the encrypted blob verbatim.
	AppendEvent(ctx context.Context, in *AppendEventRequest, opts ...grpc.CallOption) (*AppendEventResponse, error)
	// StreamEvents opens a server-side stream that pushes all events for a note
	// starting from a given sequence number. Used by clients to catch up after
	// reconnect. For secure note events the server streams the encrypted blob
	// without decrypting it.
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (NoteService_StreamEventsClient, error)
	// SearchNotes performs a server-side full-text search over normal note
	// content. Secure notes are never included in results.
	SearchNotes(ctx context.Context, in *SearchNotesRequest, opts ...grpc.CallOption) (*SearchNotesResponse, error)
	// ShareSecureNote re-wraps the CEK for one or more additional target
	// devices. The server updates the per_device_keys map in the stored
	// encrypted blobs and returns the updated event list. Only secure notes
	// can be shared via this RPC.
	ShareSecureNote(ctx context.Context, in *ShareSecureNoteRequest, opts ...grpc.CallOption) (*ShareSecureNoteResponse, error)
}

type noteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteServiceClient(cc grpc.ClientConnInterface) NoteServiceClient {
	return &noteServiceClient{cc}
}

func (c *noteServiceClient) GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error) {
	out := new(GetNoteResponse)
	err := c.cc.Invoke(ctx, NoteService_GetNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error) {
	out := new(ListNotesResponse)
	err := c.cc.Invoke(ctx, NoteService_ListNotes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error) {
	out := new(CreateNoteResponse)
	err := c.cc.Invoke(ctx, NoteService_CreateNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error) {
	out := new(DeleteNoteResponse)
	err := c.cc.Invoke(ctx, NoteService_DeleteNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) AppendEvent(ctx context.Context, in *AppendEventRequest, opts ...grpc.CallOption) (*AppendEventResponse, error) {
	out := new(AppendEventResponse)
	err := c.cc.Invoke(ctx, NoteService_AppendEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (NoteService_StreamEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &NoteService_ServiceDesc.Streams[0], NoteService_StreamEvents_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &noteServiceStreamEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NoteService_StreamEventsClient interface {
	Recv() (*EventProto, error)
	grpc.ClientStream
}

type noteServiceStreamEventsClient struct {
	grpc.ClientStream
}

func (x *noteServiceStreamEventsClient) Recv() (*EventProto, error) {
	m := new(EventProto)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *noteServiceClient) SearchNotes(ctx context.Context, in *SearchNotesRequest, opts ...grpc.CallOption) (*SearchNotesResponse, error) {
	out := new(SearchNotesResponse)
	err := c.cc.Invoke(ctx, NoteService_SearchNotes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ShareSecureNote(ctx context.Context, in *ShareSecureNoteRequest, opts ...grpc.CallOption) (*ShareSecureNoteResponse, error) {
	out := new(ShareSecureNoteResponse)
	err := c.cc.Invoke(ctx, NoteService_ShareSecureNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteServiceServer is the server API for NoteService service.
// All implementations must embed UnimplementedNoteServiceServer
// for forward compatibility
type NoteServiceServer interface {
	// GetNote returns the full header + all events for a note.
	GetNote(context.Context, *GetNoteRequest) (*GetNoteResponse, error)
	// ListNotes returns all note headers visible to the caller.
	ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error)
	// CreateNote registers a new note (header only; events follow via AppendEvent).
	CreateNote(context.Context, *CreateNoteRequest) (*CreateNoteResponse, error)
	// DeleteNote soft-deletes a note by URN.
	DeleteNote(context.Context, *DeleteNoteRequest) (*DeleteNoteResponse, error)
	// AppendEvent appends a single event to an existing note.
	// For normal notes the server stores the plaintext entries and advances the
	// index. For secure notes it stores the encrypted blob verbatim.
	AppendEvent(context.Context, *AppendEventRequest) (*AppendEventResponse, error)
	// StreamEvents opens a server-side stream that pushes all events for a note
	// starting from a given sequence number. Used by clients to catch up after
	// reconnect. For secure note events the server streams the encrypted blob
	// without decrypting it.
	StreamEvents(*StreamEventsRequest, NoteService_StreamEventsServer) error
	// SearchNotes performs a server-side full-text search over normal note
	// content. Secure notes are never included in results.
	SearchNotes(context.Context, *SearchNotesRequest) (*SearchNotesResponse, error)
	// ShareSecureNote re-wraps the CEK for one or more additional target
	// devices. The server updates the per_device_keys map in the stored
	// encrypted blobs and returns the updated event list. Only secure notes
	// can be shared via this RPC.
	ShareSecureNote(context.Context, *ShareSecureNoteRequest) (*ShareSecureNoteResponse, error)
	mustEmbedUnimplementedNoteServiceServer()
}

// UnimplementedNoteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNoteServiceServer struct {
}

func (UnimplementedNoteServiceServer) GetNote(context.Context, *GetNoteRequest) (*GetNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNote not implemented")
}
func (UnimplementedNoteServiceServer) ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotes not implemented")
}
func (UnimplementedNoteServiceServer) CreateNote(context.Context, *CreateNoteRequest) (*CreateNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNote not implemented")
}
func (UnimplementedNoteServiceServer) DeleteNote(context.Context, *DeleteNoteRequest) (*DeleteNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNote not implemented")
}
func (UnimplementedNoteServiceServer) AppendEvent(context.Context, *AppendEventRequest) (*AppendEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEvent not implemented")
}
func (UnimplementedNoteServiceServer) StreamEvents(*StreamEventsRequest, NoteService_StreamEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedNoteServiceServer) SearchNotes(context.Context, *SearchNotesRequest) (*SearchNotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchNotes not implemented")
}
func (UnimplementedNoteServiceServer) ShareSecureNote(context.Context, *ShareSecureNoteRequest) (*ShareSecureNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShareSecureNote not implemented")
}
func (UnimplementedNoteServiceServer) mustEmbedUnimplementedNoteServiceServer() {}

// UnsafeNoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteServiceServer will
// result in compilation errors.
type UnsafeNoteServiceServer interface {
	mustEmbedUnimplementedNoteServiceServer()
}

func RegisterNoteServiceServer(s grpc.ServiceRegistrar, srv NoteServiceServer) {
	s.RegisterService(&NoteService_ServiceDesc, srv)
}

func _NoteService_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_GetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).GetNote(ctx, req.(*GetNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ListNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ListNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ListNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ListNotes(ctx, req.(*ListNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_CreateNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).CreateNote(ctx, req.(*CreateNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_DeleteNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).DeleteNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_DeleteNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).DeleteNote(ctx, req.(*DeleteNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_AppendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).AppendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_AppendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).AppendEvent(ctx, req.(*AppendEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NoteServiceServer).StreamEvents(m, &noteServiceStreamEventsServer{stream})
}

type NoteService_StreamEventsServer interface {
	Send(*EventProto) error
	grpc.ServerStream
}

type noteServiceStreamEventsServer struct {
	grpc.ServerStream
}

func (x *noteServiceStreamEventsServer) Send(m *EventProto) error {
	return x.ServerStream.SendMsg(m)
}

func _NoteService_SearchNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).SearchNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_SearchNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).SearchNotes(ctx, req.(*SearchNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ShareSecureNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareSecureNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ShareSecureNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ShareSecureNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ShareSecureNote(ctx, req.(*ShareSecureNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NoteService_ServiceDesc is the grpc.ServiceDesc for NoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notx.v1.NoteService",
	HandlerType: (*NoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNote",
			Handler:    _NoteService_GetNote_Handler,
		},
		{
			MethodName: "ListNotes",
			Handler:    _NoteService_ListNotes_Handler,
		},
		{
			MethodName: "CreateNote",
			Handler:    _NoteService_CreateNote_Handler,
		},
		{
			MethodName: "DeleteNote",
			Handler:    _NoteService_DeleteNote_Handler,
		},
		{
			MethodName: "AppendEvent",
			Handler:    _NoteService_AppendEvent_Handler,
		},
		{
			MethodName: "SearchNotes",
			Handler:    _NoteService_SearchNotes_Handler,
		},
		{
			MethodName: "ShareSecureNote",
			Handler:    _NoteService_ShareSecureNote_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _NoteService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "notx.proto",
}

const (
	DeviceService_RegisterDevice_FullMethodName     = "/notx.v1.DeviceService/RegisterDevice"
	DeviceService_GetDevicePublicKey_FullMethodName = "/notx.v1.DeviceService/GetDevicePublicKey"
	DeviceService_ListDevices_FullMethodName        = "/notx.v1.DeviceService/ListDevices"
	DeviceService_RevokeDevice_FullMethodName       = "/notx.v1.DeviceService/RevokeDevice"
	DeviceService_InitiatePairing_FullMethodName    = "/notx.v1.DeviceService/InitiatePairing"
	DeviceService_CompletePairing_FullMethodName    = "/notx.v1.DeviceService/CompletePairing"
)

// DeviceServiceClient is the client API for DeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceServiceClient interface {
	// RegisterDevice registers a new device by storing its public key.
	// The private key must never appear in this request.
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error)
	// GetDevicePublicKey retrieves the public key for a registered device.
	// Used by other devices when wrapping a CEK for that device.
	GetDevicePublicKey(ctx context.Context, in *GetDevicePublicKeyRequest, opts ...grpc.CallOption) (*GetDevicePublicKeyResponse, error)
	// ListDevices returns all devices registered to the authenticated user.
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	// RevokeDevice removes a device from the registry. Future secure note
	// shares will not include the revoked device.
	RevokeDevice(ctx context.Context, in *RevokeDeviceRequest, opts ...grpc.CallOption) (*RevokeDeviceResponse, error)
	// InitiatePairing starts the browser-pairing flow and returns a short-lived
	// session token that the browser embeds in its QR code.
	InitiatePairing(ctx context.Context, in *InitiatePairingRequest, opts ...grpc.CallOption) (*InitiatePairingResponse, error)
	// CompletePairing is called by an already-trusted device after scanning the
	// browser QR code. It registers the browser device and closes the session.
	CompletePairing(ctx context.Context, in *CompletePairingRequest, opts ...grpc.CallOption) (*CompletePairingResponse, error)
}

type deviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceServiceClient(cc grpc.ClientConnInterface) DeviceServiceClient {
	return &deviceServiceClient{cc}
}

func (c *deviceServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error) {
	out := new(RegisterDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceService_RegisterDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) GetDevicePublicKey(ctx context.Context, in *GetDevicePublicKeyRequest, opts ...grpc.CallOption) (*GetDevicePublicKeyResponse, error) {
	out := new(GetDevicePublicKeyResponse)
	err := c.cc.Invoke(ctx, DeviceService_GetDevicePublicKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, DeviceService_ListDevices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) RevokeDevice(ctx context.Context, in *RevokeDeviceRequest, opts ...grpc.CallOption) (*RevokeDeviceResponse, error) {
	out := new(RevokeDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceService_RevokeDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) InitiatePairing(ctx context.Context, in *InitiatePairingRequest, opts ...grpc.CallOption) (*InitiatePairingResponse, error) {
	out := new(InitiatePairingResponse)
	err := c.cc.Invoke(ctx, DeviceService_InitiatePairing_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) CompletePairing(ctx context.Context, in *CompletePairingRequest, opts ...grpc.CallOption) (*CompletePairingResponse, error) {
	out := new(CompletePairingResponse)
	err := c.cc.Invoke(ctx, DeviceService_CompletePairing_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServiceServer is the server API for DeviceService service.
// All implementations must embed UnimplementedDeviceServiceServer
// for forward compatibility
type DeviceServiceServer interface {
	// RegisterDevice registers a new device by storing its public key.
	// The private key must never appear in this request.
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error)
	// GetDevicePublicKey retrieves the public key for a registered device.
	// Used by other devices when wrapping a CEK for that device.
	GetDevicePublicKey(context.Context, *GetDevicePublicKeyRequest) (*GetDevicePublicKeyResponse, error)
	// ListDevices returns all devices registered to the authenticated user.
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	// RevokeDevice removes a device from the registry. Future secure note
	// shares will not include the revoked device.
	RevokeDevice(context.Context, *RevokeDeviceRequest) (*RevokeDeviceResponse, error)
	// InitiatePairing starts the browser-pairing flow and returns a short-lived
	// session token that the browser embeds in its QR code.
	InitiatePairing(context.Context, *InitiatePairingRequest) (*InitiatePairingResponse, error)
	// CompletePairing is called by an already-trusted device after scanning the
	// browser QR code. It registers the browser device and closes the session.
	CompletePairing(context.Context, *CompletePairingRequest) (*CompletePairingResponse, error)
	mustEmbedUnimplementedDeviceServiceServer()
}

// UnimplementedDeviceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeviceServiceServer struct {
}

func (UnimplementedDeviceServiceServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedDeviceServiceServer) GetDevicePublicKey(context.Context, *GetDevicePublicKeyRequest) (*GetDevicePublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevicePublicKey not implemented")
}
func (UnimplementedDeviceServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedDeviceServiceServer) RevokeDevice(context.Context, *RevokeDeviceRequest) (*RevokeDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeDevice not implemented")
}
func (UnimplementedDeviceServiceServer) InitiatePairing(context.Context, *InitiatePairingRequest) (*InitiatePairingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiatePairing not implemented")
}
func (UnimplementedDeviceServiceServer) CompletePairing(context.Context, *CompletePairingRequest) (*CompletePairingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompletePairing not implemented")
}
func (UnimplementedDeviceServiceServer) mustEmbedUnimplementedDeviceServiceServer() {}

// UnsafeDeviceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceServiceServer will
// result in compilation errors.
type UnsafeDeviceServiceServer interface {
	mustEmbedUnimplementedDeviceServiceServer()
}

func RegisterDeviceServiceServer(s grpc.ServiceRegistrar, srv DeviceServiceServer) {
	s.RegisterService(&DeviceService_ServiceDesc, srv)
}

func _DeviceService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_GetDevicePublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevicePublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).GetDevicePublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_GetDevicePublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).GetDevicePublicKey(ctx, req.(*GetDevicePublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_RevokeDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).RevokeDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_RevokeDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).RevokeDevice(ctx, req.(*RevokeDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_InitiatePairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiatePairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).InitiatePairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_InitiatePairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).InitiatePairing(ctx, req.(*InitiatePairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_CompletePairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletePairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).CompletePairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_CompletePairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).CompletePairing(ctx, req.(*CompletePairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceService_ServiceDesc is the grpc.ServiceDesc for DeviceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notx.v1.DeviceService",
	HandlerType: (*DeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _DeviceService_RegisterDevice_Handler,
		},
		{
			MethodName: "GetDevicePublicKey",
			Handler:    _DeviceService_GetDevicePublicKey_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _DeviceService_ListDevices_Handler,
		},
		{
			MethodName: "RevokeDevice",
			Handler:    _DeviceService_RevokeDevice_Handler,
		},
		{
			MethodName: "InitiatePairing",
			Handler:    _DeviceService_InitiatePairing_Handler,
		},
		{
			MethodName: "CompletePairing",
			Handler:    _DeviceService_CompletePairing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notx.proto",
}
