// Code generated by hand to match relay.proto — DO NOT EDIT via protoc.
// Proto package: notx.v1
// Go package:    github.com/zebaqui/notx-engine/internal/server/proto

package notxpb

// ─────────────────────────────────────────────────────────────────────────────
// HttpRequest
// ─────────────────────────────────────────────────────────────────────────────

type HttpRequest struct {
	Method  string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url     string            `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body    []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *HttpRequest) Reset()         {}
func (x *HttpRequest) String() string { return x.Method + " " + x.Url }
func (x *HttpRequest) ProtoMessage()  {}

func (x *HttpRequest) GetMethod() string             { return x.Method }
func (x *HttpRequest) GetUrl() string                { return x.Url }
func (x *HttpRequest) GetHeaders() map[string]string { return x.Headers }
func (x *HttpRequest) GetBody() []byte               { return x.Body }

// ─────────────────────────────────────────────────────────────────────────────
// HttpResponse
// ─────────────────────────────────────────────────────────────────────────────

type HttpResponse struct {
	Status     int32             `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers    map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body       []byte            `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	DurationMs int64             `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
}

func (x *HttpResponse) Reset()         {}
func (x *HttpResponse) String() string { return "" }
func (x *HttpResponse) ProtoMessage()  {}

func (x *HttpResponse) GetStatus() int32              { return x.Status }
func (x *HttpResponse) GetHeaders() map[string]string { return x.Headers }
func (x *HttpResponse) GetBody() []byte               { return x.Body }
func (x *HttpResponse) GetDurationMs() int64          { return x.DurationMs }

// ─────────────────────────────────────────────────────────────────────────────
// ExecuteRequest / ExecuteResponse
// ─────────────────────────────────────────────────────────────────────────────

type ExecuteRequest struct {
	DeviceUrn string            `protobuf:"bytes,1,opt,name=device_urn,json=deviceUrn,proto3" json:"device_urn,omitempty"`
	Request   *HttpRequest      `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Variables map[string]string `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ExecuteRequest) Reset()         {}
func (x *ExecuteRequest) String() string { return "" }
func (x *ExecuteRequest) ProtoMessage()  {}

func (x *ExecuteRequest) GetDeviceUrn() string            { return x.DeviceUrn }
func (x *ExecuteRequest) GetRequest() *HttpRequest        { return x.Request }
func (x *ExecuteRequest) GetVariables() map[string]string { return x.Variables }

type ExecuteResponse struct {
	Response *HttpResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *ExecuteResponse) Reset()         {}
func (x *ExecuteResponse) String() string { return "" }
func (x *ExecuteResponse) ProtoMessage()  {}

func (x *ExecuteResponse) GetResponse() *HttpResponse { return x.Response }

// ─────────────────────────────────────────────────────────────────────────────
// Step / ExecuteFlowRequest / StepResult / ExecuteFlowResponse
// ─────────────────────────────────────────────────────────────────────────────

type Step struct {
	Id      string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Request *HttpRequest      `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Extract map[string]string `protobuf:"bytes,3,rep,name=extract,proto3" json:"extract,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Step) Reset()         {}
func (x *Step) String() string { return x.Id }
func (x *Step) ProtoMessage()  {}

func (x *Step) GetId() string                 { return x.Id }
func (x *Step) GetRequest() *HttpRequest      { return x.Request }
func (x *Step) GetExtract() map[string]string { return x.Extract }

type ExecuteFlowRequest struct {
	DeviceUrn string            `protobuf:"bytes,1,opt,name=device_urn,json=deviceUrn,proto3" json:"device_urn,omitempty"`
	Steps     []*Step           `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	Variables map[string]string `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ExecuteFlowRequest) Reset()         {}
func (x *ExecuteFlowRequest) String() string { return "" }
func (x *ExecuteFlowRequest) ProtoMessage()  {}

func (x *ExecuteFlowRequest) GetDeviceUrn() string            { return x.DeviceUrn }
func (x *ExecuteFlowRequest) GetSteps() []*Step               { return x.Steps }
func (x *ExecuteFlowRequest) GetVariables() map[string]string { return x.Variables }

type StepResult struct {
	Id       string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Response *HttpResponse `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *StepResult) Reset()         {}
func (x *StepResult) String() string { return x.Id }
func (x *StepResult) ProtoMessage()  {}

func (x *StepResult) GetId() string              { return x.Id }
func (x *StepResult) GetResponse() *HttpResponse { return x.Response }

type ExecuteFlowResponse struct {
	Results   []*StepResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Variables map[string]string `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ExecuteFlowResponse) Reset()         {}
func (x *ExecuteFlowResponse) String() string { return "" }
func (x *ExecuteFlowResponse) ProtoMessage()  {}

func (x *ExecuteFlowResponse) GetResults() []*StepResult       { return x.Results }
func (x *ExecuteFlowResponse) GetVariables() map[string]string { return x.Variables }

// ─────────────────────────────────────────────────────────────────────────────
// RelayErrorDetail
// ─────────────────────────────────────────────────────────────────────────────

type RelayErrorDetail struct {
	StepId      string `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	DurationMs  int64  `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	BlockedHost string `protobuf:"bytes,3,opt,name=blocked_host,json=blockedHost,proto3" json:"blocked_host,omitempty"`
}

func (x *RelayErrorDetail) Reset()         {}
func (x *RelayErrorDetail) String() string { return "" }
func (x *RelayErrorDetail) ProtoMessage()  {}

func (x *RelayErrorDetail) GetStepId() string      { return x.StepId }
func (x *RelayErrorDetail) GetDurationMs() int64   { return x.DurationMs }
func (x *RelayErrorDetail) GetBlockedHost() string { return x.BlockedHost }
