// Code generated by hand to match relay.proto — DO NOT EDIT via protoc.

package notxpb

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ─────────────────────────────────────────────────────────────────────────────
// Service descriptor constants
// ─────────────────────────────────────────────────────────────────────────────

const (
	RelayService_Execute_FullMethodName     = "/notx.v1.RelayService/Execute"
	RelayService_ExecuteFlow_FullMethodName = "/notx.v1.RelayService/ExecuteFlow"
)

// ─────────────────────────────────────────────────────────────────────────────
// Server interface
// ─────────────────────────────────────────────────────────────────────────────

// RelayServiceServer is the server-side interface that implementations must
// satisfy.
type RelayServiceServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	ExecuteFlow(context.Context, *ExecuteFlowRequest) (*ExecuteFlowResponse, error)
	mustEmbedUnimplementedRelayServiceServer()
}

// UnimplementedRelayServiceServer provides forward-compatible no-op
// implementations of all RPCs.  Embed this in any concrete server.
type UnimplementedRelayServiceServer struct{}

func (UnimplementedRelayServiceServer) Execute(_ context.Context, _ *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedRelayServiceServer) ExecuteFlow(_ context.Context, _ *ExecuteFlowRequest) (*ExecuteFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteFlow not implemented")
}
func (UnimplementedRelayServiceServer) mustEmbedUnimplementedRelayServiceServer() {}

// UnsafeRelayServiceServer may be embedded to opt out of forward compatibility.
// Use of this interface is not recommended.
type UnsafeRelayServiceServer interface {
	mustEmbedUnimplementedRelayServiceServer()
}

// ─────────────────────────────────────────────────────────────────────────────
// Registration helper
// ─────────────────────────────────────────────────────────────────────────────

func RegisterRelayServiceServer(s grpc.ServiceRegistrar, srv RelayServiceServer) {
	s.RegisterService(&RelayService_ServiceDesc, srv)
}

// ─────────────────────────────────────────────────────────────────────────────
// Client interface + constructor
// ─────────────────────────────────────────────────────────────────────────────

type RelayServiceClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	ExecuteFlow(ctx context.Context, in *ExecuteFlowRequest, opts ...grpc.CallOption) (*ExecuteFlowResponse, error)
}

type relayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayServiceClient(cc grpc.ClientConnInterface) RelayServiceClient {
	return &relayServiceClient{cc}
}

func (c *relayServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, RelayService_Execute_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayServiceClient) ExecuteFlow(ctx context.Context, in *ExecuteFlowRequest, opts ...grpc.CallOption) (*ExecuteFlowResponse, error) {
	out := new(ExecuteFlowResponse)
	err := c.cc.Invoke(ctx, RelayService_ExecuteFlow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Server-side handler plumbing
// ─────────────────────────────────────────────────────────────────────────────

func _RelayService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayService_ExecuteFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).ExecuteFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_ExecuteFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).ExecuteFlow(ctx, req.(*ExecuteFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ─────────────────────────────────────────────────────────────────────────────
// Service descriptor
// ─────────────────────────────────────────────────────────────────────────────

var RelayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notx.v1.RelayService",
	HandlerType: (*RelayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _RelayService_Execute_Handler,
		},
		{
			MethodName: "ExecuteFlow",
			Handler:    _RelayService_ExecuteFlow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relay.proto",
}
