// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: device.proto

package notxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DeviceService_RegisterDevice_FullMethodName     = "/notx.v1.DeviceService/RegisterDevice"
	DeviceService_GetDevicePublicKey_FullMethodName = "/notx.v1.DeviceService/GetDevicePublicKey"
	DeviceService_ListDevices_FullMethodName        = "/notx.v1.DeviceService/ListDevices"
	DeviceService_RevokeDevice_FullMethodName       = "/notx.v1.DeviceService/RevokeDevice"
	DeviceService_InitiatePairing_FullMethodName    = "/notx.v1.DeviceService/InitiatePairing"
	DeviceService_CompletePairing_FullMethodName    = "/notx.v1.DeviceService/CompletePairing"
)

// DeviceServiceClient is the client API for DeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceServiceClient interface {
	// RegisterDevice registers a new device by storing its public key.
	// The private key must never appear in this request.
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error)
	// GetDevicePublicKey retrieves the public key for a registered device.
	// Used by other devices when wrapping a CEK for that device.
	GetDevicePublicKey(ctx context.Context, in *GetDevicePublicKeyRequest, opts ...grpc.CallOption) (*GetDevicePublicKeyResponse, error)
	// ListDevices returns all devices registered to the authenticated user.
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	// RevokeDevice removes a device from the registry. Future secure note
	// shares will not include the revoked device.
	RevokeDevice(ctx context.Context, in *RevokeDeviceRequest, opts ...grpc.CallOption) (*RevokeDeviceResponse, error)
	// InitiatePairing starts the browser-pairing flow and returns a short-lived
	// session token that the browser embeds in its QR code.
	InitiatePairing(ctx context.Context, in *InitiatePairingRequest, opts ...grpc.CallOption) (*InitiatePairingResponse, error)
	// CompletePairing is called by an already-trusted device after scanning the
	// browser QR code. It registers the browser device and closes the session.
	CompletePairing(ctx context.Context, in *CompletePairingRequest, opts ...grpc.CallOption) (*CompletePairingResponse, error)
}

type deviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceServiceClient(cc grpc.ClientConnInterface) DeviceServiceClient {
	return &deviceServiceClient{cc}
}

func (c *deviceServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error) {
	out := new(RegisterDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceService_RegisterDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) GetDevicePublicKey(ctx context.Context, in *GetDevicePublicKeyRequest, opts ...grpc.CallOption) (*GetDevicePublicKeyResponse, error) {
	out := new(GetDevicePublicKeyResponse)
	err := c.cc.Invoke(ctx, DeviceService_GetDevicePublicKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, DeviceService_ListDevices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) RevokeDevice(ctx context.Context, in *RevokeDeviceRequest, opts ...grpc.CallOption) (*RevokeDeviceResponse, error) {
	out := new(RevokeDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceService_RevokeDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) InitiatePairing(ctx context.Context, in *InitiatePairingRequest, opts ...grpc.CallOption) (*InitiatePairingResponse, error) {
	out := new(InitiatePairingResponse)
	err := c.cc.Invoke(ctx, DeviceService_InitiatePairing_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) CompletePairing(ctx context.Context, in *CompletePairingRequest, opts ...grpc.CallOption) (*CompletePairingResponse, error) {
	out := new(CompletePairingResponse)
	err := c.cc.Invoke(ctx, DeviceService_CompletePairing_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServiceServer is the server API for DeviceService service.
// All implementations must embed UnimplementedDeviceServiceServer
// for forward compatibility
type DeviceServiceServer interface {
	// RegisterDevice registers a new device by storing its public key.
	// The private key must never appear in this request.
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error)
	// GetDevicePublicKey retrieves the public key for a registered device.
	// Used by other devices when wrapping a CEK for that device.
	GetDevicePublicKey(context.Context, *GetDevicePublicKeyRequest) (*GetDevicePublicKeyResponse, error)
	// ListDevices returns all devices registered to the authenticated user.
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	// RevokeDevice removes a device from the registry. Future secure note
	// shares will not include the revoked device.
	RevokeDevice(context.Context, *RevokeDeviceRequest) (*RevokeDeviceResponse, error)
	// InitiatePairing starts the browser-pairing flow and returns a short-lived
	// session token that the browser embeds in its QR code.
	InitiatePairing(context.Context, *InitiatePairingRequest) (*InitiatePairingResponse, error)
	// CompletePairing is called by an already-trusted device after scanning the
	// browser QR code. It registers the browser device and closes the session.
	CompletePairing(context.Context, *CompletePairingRequest) (*CompletePairingResponse, error)
	mustEmbedUnimplementedDeviceServiceServer()
}

// UnimplementedDeviceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeviceServiceServer struct {
}

func (UnimplementedDeviceServiceServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedDeviceServiceServer) GetDevicePublicKey(context.Context, *GetDevicePublicKeyRequest) (*GetDevicePublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevicePublicKey not implemented")
}
func (UnimplementedDeviceServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedDeviceServiceServer) RevokeDevice(context.Context, *RevokeDeviceRequest) (*RevokeDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeDevice not implemented")
}
func (UnimplementedDeviceServiceServer) InitiatePairing(context.Context, *InitiatePairingRequest) (*InitiatePairingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiatePairing not implemented")
}
func (UnimplementedDeviceServiceServer) CompletePairing(context.Context, *CompletePairingRequest) (*CompletePairingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompletePairing not implemented")
}
func (UnimplementedDeviceServiceServer) mustEmbedUnimplementedDeviceServiceServer() {}

// UnsafeDeviceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceServiceServer will
// result in compilation errors.
type UnsafeDeviceServiceServer interface {
	mustEmbedUnimplementedDeviceServiceServer()
}

func RegisterDeviceServiceServer(s grpc.ServiceRegistrar, srv DeviceServiceServer) {
	s.RegisterService(&DeviceService_ServiceDesc, srv)
}

func _DeviceService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_GetDevicePublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevicePublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).GetDevicePublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_GetDevicePublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).GetDevicePublicKey(ctx, req.(*GetDevicePublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_RevokeDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).RevokeDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_RevokeDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).RevokeDevice(ctx, req.(*RevokeDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_InitiatePairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiatePairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).InitiatePairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_InitiatePairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).InitiatePairing(ctx, req.(*InitiatePairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_CompletePairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletePairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).CompletePairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_CompletePairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).CompletePairing(ctx, req.(*CompletePairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceService_ServiceDesc is the grpc.ServiceDesc for DeviceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notx.v1.DeviceService",
	HandlerType: (*DeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _DeviceService_RegisterDevice_Handler,
		},
		{
			MethodName: "GetDevicePublicKey",
			Handler:    _DeviceService_GetDevicePublicKey_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _DeviceService_ListDevices_Handler,
		},
		{
			MethodName: "RevokeDevice",
			Handler:    _DeviceService_RevokeDevice_Handler,
		},
		{
			MethodName: "InitiatePairing",
			Handler:    _DeviceService_InitiatePairing_Handler,
		},
		{
			MethodName: "CompletePairing",
			Handler:    _DeviceService_CompletePairing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "device.proto",
}

const (
	DeviceAdminService_AdminRegisterDevice_FullMethodName = "/notx.v1.DeviceAdminService/AdminRegisterDevice"
	DeviceAdminService_GetDevice_FullMethodName           = "/notx.v1.DeviceAdminService/GetDevice"
	DeviceAdminService_UpdateDevice_FullMethodName        = "/notx.v1.DeviceAdminService/UpdateDevice"
	DeviceAdminService_GetDeviceStatus_FullMethodName     = "/notx.v1.DeviceAdminService/GetDeviceStatus"
	DeviceAdminService_ApproveDevice_FullMethodName       = "/notx.v1.DeviceAdminService/ApproveDevice"
	DeviceAdminService_RejectDevice_FullMethodName        = "/notx.v1.DeviceAdminService/RejectDevice"
	DeviceAdminService_AdminListDevices_FullMethodName    = "/notx.v1.DeviceAdminService/AdminListDevices"
	DeviceAdminService_AdminRevokeDevice_FullMethodName   = "/notx.v1.DeviceAdminService/AdminRevokeDevice"
)

// DeviceAdminServiceClient is the client API for DeviceAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceAdminServiceClient interface {
	// AdminRegisterDevice is the single registration path used by the admin
	// layer. It accepts role and approval_status overrides supplied after the
	// HTTP layer has validated any admin passphrase.
	AdminRegisterDevice(ctx context.Context, in *AdminRegisterDeviceRequest, opts ...grpc.CallOption) (*AdminRegisterDeviceResponse, error)
	// GetDevice returns the extended descriptor for a single device.
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
	// UpdateDevice mutates mutable fields on a device record.
	// Only the paths listed in update_mask are applied.
	UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*UpdateDeviceResponse, error)
	// GetDeviceStatus returns the approval/revocation status of a device.
	// Callers should check approval_status == APPROVAL_STATUS_APPROVED rather
	// than relying on a separate boolean field.
	GetDeviceStatus(ctx context.Context, in *GetDeviceStatusRequest, opts ...grpc.CallOption) (*GetDeviceStatusResponse, error)
	// ApproveDevice grants approved status to a pending device.
	ApproveDevice(ctx context.Context, in *ApproveDeviceRequest, opts ...grpc.CallOption) (*ApproveDeviceResponse, error)
	// RejectDevice denies a pending device registration.
	RejectDevice(ctx context.Context, in *RejectDeviceRequest, opts ...grpc.CallOption) (*RejectDeviceResponse, error)
	// AdminListDevices returns the full list of devices, optionally filtered by
	// owner and including revoked devices, with cursor-based pagination.
	AdminListDevices(ctx context.Context, in *AdminListDevicesRequest, opts ...grpc.CallOption) (*AdminListDevicesResponse, error)
	// AdminRevokeDevice revokes a device and returns its URN plus confirmation.
	AdminRevokeDevice(ctx context.Context, in *AdminRevokeDeviceRequest, opts ...grpc.CallOption) (*AdminRevokeDeviceResponse, error)
}

type deviceAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceAdminServiceClient(cc grpc.ClientConnInterface) DeviceAdminServiceClient {
	return &deviceAdminServiceClient{cc}
}

func (c *deviceAdminServiceClient) AdminRegisterDevice(ctx context.Context, in *AdminRegisterDeviceRequest, opts ...grpc.CallOption) (*AdminRegisterDeviceResponse, error) {
	out := new(AdminRegisterDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceAdminService_AdminRegisterDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAdminServiceClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error) {
	out := new(GetDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceAdminService_GetDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAdminServiceClient) UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*UpdateDeviceResponse, error) {
	out := new(UpdateDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceAdminService_UpdateDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAdminServiceClient) GetDeviceStatus(ctx context.Context, in *GetDeviceStatusRequest, opts ...grpc.CallOption) (*GetDeviceStatusResponse, error) {
	out := new(GetDeviceStatusResponse)
	err := c.cc.Invoke(ctx, DeviceAdminService_GetDeviceStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAdminServiceClient) ApproveDevice(ctx context.Context, in *ApproveDeviceRequest, opts ...grpc.CallOption) (*ApproveDeviceResponse, error) {
	out := new(ApproveDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceAdminService_ApproveDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAdminServiceClient) RejectDevice(ctx context.Context, in *RejectDeviceRequest, opts ...grpc.CallOption) (*RejectDeviceResponse, error) {
	out := new(RejectDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceAdminService_RejectDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAdminServiceClient) AdminListDevices(ctx context.Context, in *AdminListDevicesRequest, opts ...grpc.CallOption) (*AdminListDevicesResponse, error) {
	out := new(AdminListDevicesResponse)
	err := c.cc.Invoke(ctx, DeviceAdminService_AdminListDevices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAdminServiceClient) AdminRevokeDevice(ctx context.Context, in *AdminRevokeDeviceRequest, opts ...grpc.CallOption) (*AdminRevokeDeviceResponse, error) {
	out := new(AdminRevokeDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceAdminService_AdminRevokeDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceAdminServiceServer is the server API for DeviceAdminService service.
// All implementations must embed UnimplementedDeviceAdminServiceServer
// for forward compatibility
type DeviceAdminServiceServer interface {
	// AdminRegisterDevice is the single registration path used by the admin
	// layer. It accepts role and approval_status overrides supplied after the
	// HTTP layer has validated any admin passphrase.
	AdminRegisterDevice(context.Context, *AdminRegisterDeviceRequest) (*AdminRegisterDeviceResponse, error)
	// GetDevice returns the extended descriptor for a single device.
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	// UpdateDevice mutates mutable fields on a device record.
	// Only the paths listed in update_mask are applied.
	UpdateDevice(context.Context, *UpdateDeviceRequest) (*UpdateDeviceResponse, error)
	// GetDeviceStatus returns the approval/revocation status of a device.
	// Callers should check approval_status == APPROVAL_STATUS_APPROVED rather
	// than relying on a separate boolean field.
	GetDeviceStatus(context.Context, *GetDeviceStatusRequest) (*GetDeviceStatusResponse, error)
	// ApproveDevice grants approved status to a pending device.
	ApproveDevice(context.Context, *ApproveDeviceRequest) (*ApproveDeviceResponse, error)
	// RejectDevice denies a pending device registration.
	RejectDevice(context.Context, *RejectDeviceRequest) (*RejectDeviceResponse, error)
	// AdminListDevices returns the full list of devices, optionally filtered by
	// owner and including revoked devices, with cursor-based pagination.
	AdminListDevices(context.Context, *AdminListDevicesRequest) (*AdminListDevicesResponse, error)
	// AdminRevokeDevice revokes a device and returns its URN plus confirmation.
	AdminRevokeDevice(context.Context, *AdminRevokeDeviceRequest) (*AdminRevokeDeviceResponse, error)
	mustEmbedUnimplementedDeviceAdminServiceServer()
}

// UnimplementedDeviceAdminServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeviceAdminServiceServer struct {
}

func (UnimplementedDeviceAdminServiceServer) AdminRegisterDevice(context.Context, *AdminRegisterDeviceRequest) (*AdminRegisterDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminRegisterDevice not implemented")
}
func (UnimplementedDeviceAdminServiceServer) GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevice not implemented")
}
func (UnimplementedDeviceAdminServiceServer) UpdateDevice(context.Context, *UpdateDeviceRequest) (*UpdateDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDevice not implemented")
}
func (UnimplementedDeviceAdminServiceServer) GetDeviceStatus(context.Context, *GetDeviceStatusRequest) (*GetDeviceStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceStatus not implemented")
}
func (UnimplementedDeviceAdminServiceServer) ApproveDevice(context.Context, *ApproveDeviceRequest) (*ApproveDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveDevice not implemented")
}
func (UnimplementedDeviceAdminServiceServer) RejectDevice(context.Context, *RejectDeviceRequest) (*RejectDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectDevice not implemented")
}
func (UnimplementedDeviceAdminServiceServer) AdminListDevices(context.Context, *AdminListDevicesRequest) (*AdminListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminListDevices not implemented")
}
func (UnimplementedDeviceAdminServiceServer) AdminRevokeDevice(context.Context, *AdminRevokeDeviceRequest) (*AdminRevokeDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminRevokeDevice not implemented")
}
func (UnimplementedDeviceAdminServiceServer) mustEmbedUnimplementedDeviceAdminServiceServer() {}

// UnsafeDeviceAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceAdminServiceServer will
// result in compilation errors.
type UnsafeDeviceAdminServiceServer interface {
	mustEmbedUnimplementedDeviceAdminServiceServer()
}

func RegisterDeviceAdminServiceServer(s grpc.ServiceRegistrar, srv DeviceAdminServiceServer) {
	s.RegisterService(&DeviceAdminService_ServiceDesc, srv)
}

func _DeviceAdminService_AdminRegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAdminServiceServer).AdminRegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAdminService_AdminRegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAdminServiceServer).AdminRegisterDevice(ctx, req.(*AdminRegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAdminService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAdminServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAdminService_GetDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAdminServiceServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAdminService_UpdateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAdminServiceServer).UpdateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAdminService_UpdateDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAdminServiceServer).UpdateDevice(ctx, req.(*UpdateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAdminService_GetDeviceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAdminServiceServer).GetDeviceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAdminService_GetDeviceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAdminServiceServer).GetDeviceStatus(ctx, req.(*GetDeviceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAdminService_ApproveDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAdminServiceServer).ApproveDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAdminService_ApproveDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAdminServiceServer).ApproveDevice(ctx, req.(*ApproveDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAdminService_RejectDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAdminServiceServer).RejectDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAdminService_RejectDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAdminServiceServer).RejectDevice(ctx, req.(*RejectDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAdminService_AdminListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAdminServiceServer).AdminListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAdminService_AdminListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAdminServiceServer).AdminListDevices(ctx, req.(*AdminListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAdminService_AdminRevokeDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRevokeDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAdminServiceServer).AdminRevokeDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAdminService_AdminRevokeDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAdminServiceServer).AdminRevokeDevice(ctx, req.(*AdminRevokeDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceAdminService_ServiceDesc is the grpc.ServiceDesc for DeviceAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notx.v1.DeviceAdminService",
	HandlerType: (*DeviceAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminRegisterDevice",
			Handler:    _DeviceAdminService_AdminRegisterDevice_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _DeviceAdminService_GetDevice_Handler,
		},
		{
			MethodName: "UpdateDevice",
			Handler:    _DeviceAdminService_UpdateDevice_Handler,
		},
		{
			MethodName: "GetDeviceStatus",
			Handler:    _DeviceAdminService_GetDeviceStatus_Handler,
		},
		{
			MethodName: "ApproveDevice",
			Handler:    _DeviceAdminService_ApproveDevice_Handler,
		},
		{
			MethodName: "RejectDevice",
			Handler:    _DeviceAdminService_RejectDevice_Handler,
		},
		{
			MethodName: "AdminListDevices",
			Handler:    _DeviceAdminService_AdminListDevices_Handler,
		},
		{
			MethodName: "AdminRevokeDevice",
			Handler:    _DeviceAdminService_AdminRevokeDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "device.proto",
}
