// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: link.proto

package notxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LinkService_UpsertAnchor_FullMethodName       = "/notx.v1.LinkService/UpsertAnchor"
	LinkService_DeleteAnchor_FullMethodName       = "/notx.v1.LinkService/DeleteAnchor"
	LinkService_GetAnchor_FullMethodName          = "/notx.v1.LinkService/GetAnchor"
	LinkService_ListAnchors_FullMethodName        = "/notx.v1.LinkService/ListAnchors"
	LinkService_UpsertBacklink_FullMethodName     = "/notx.v1.LinkService/UpsertBacklink"
	LinkService_DeleteBacklink_FullMethodName     = "/notx.v1.LinkService/DeleteBacklink"
	LinkService_ListBacklinks_FullMethodName      = "/notx.v1.LinkService/ListBacklinks"
	LinkService_ListOutboundLinks_FullMethodName  = "/notx.v1.LinkService/ListOutboundLinks"
	LinkService_GetReferrers_FullMethodName       = "/notx.v1.LinkService/GetReferrers"
	LinkService_RecentBacklinks_FullMethodName    = "/notx.v1.LinkService/RecentBacklinks"
	LinkService_UpsertExternalLink_FullMethodName = "/notx.v1.LinkService/UpsertExternalLink"
	LinkService_DeleteExternalLink_FullMethodName = "/notx.v1.LinkService/DeleteExternalLink"
	LinkService_ListExternalLinks_FullMethodName  = "/notx.v1.LinkService/ListExternalLinks"
)

// LinkServiceClient is the client API for LinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkServiceClient interface {
	// UpsertAnchor inserts or updates an anchor in the server-side index.
	UpsertAnchor(ctx context.Context, in *UpsertAnchorRequest, opts ...grpc.CallOption) (*UpsertAnchorResponse, error)
	// DeleteAnchor removes an anchor. When tombstone=true the anchor is marked
	// deprecated instead of deleted, preserving referrer awareness.
	DeleteAnchor(ctx context.Context, in *DeleteAnchorRequest, opts ...grpc.CallOption) (*DeleteAnchorResponse, error)
	// GetAnchor retrieves a single anchor by note URN and anchor ID.
	GetAnchor(ctx context.Context, in *GetAnchorRequest, opts ...grpc.CallOption) (*GetAnchorResponse, error)
	// ListAnchors returns all anchors declared in a note, ordered by line ASC.
	ListAnchors(ctx context.Context, in *ListAnchorsRequest, opts ...grpc.CallOption) (*ListAnchorsResponse, error)
	// UpsertBacklink inserts or updates a backlink record.
	UpsertBacklink(ctx context.Context, in *UpsertBacklinkRequest, opts ...grpc.CallOption) (*UpsertBacklinkResponse, error)
	// DeleteBacklink removes a specific backlink record.
	DeleteBacklink(ctx context.Context, in *DeleteBacklinkRequest, opts ...grpc.CallOption) (*DeleteBacklinkResponse, error)
	// ListBacklinks returns inbound backlinks for a note (optionally filtered by anchor).
	ListBacklinks(ctx context.Context, in *ListBacklinksRequest, opts ...grpc.CallOption) (*ListBacklinksResponse, error)
	// ListOutboundLinks returns all outbound backlink records from a source note.
	ListOutboundLinks(ctx context.Context, in *ListOutboundLinksRequest, opts ...grpc.CallOption) (*ListOutboundLinksResponse, error)
	// GetReferrers returns the URNs of all notes that link to a specific anchor.
	GetReferrers(ctx context.Context, in *GetReferrersRequest, opts ...grpc.CallOption) (*GetReferrersResponse, error)
	// RecentBacklinks returns the most recently created backlinks across all notes,
	// with optional filtering. Used for browse/admin views.
	RecentBacklinks(ctx context.Context, in *RecentBacklinksRequest, opts ...grpc.CallOption) (*RecentBacklinksResponse, error)
	// UpsertExternalLink inserts or updates an external link record.
	UpsertExternalLink(ctx context.Context, in *UpsertExternalLinkRequest, opts ...grpc.CallOption) (*UpsertExternalLinkResponse, error)
	// DeleteExternalLink removes an external link record.
	DeleteExternalLink(ctx context.Context, in *DeleteExternalLinkRequest, opts ...grpc.CallOption) (*DeleteExternalLinkResponse, error)
	// ListExternalLinks returns all external links from a source note.
	ListExternalLinks(ctx context.Context, in *ListExternalLinksRequest, opts ...grpc.CallOption) (*ListExternalLinksResponse, error)
}

type linkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkServiceClient(cc grpc.ClientConnInterface) LinkServiceClient {
	return &linkServiceClient{cc}
}

func (c *linkServiceClient) UpsertAnchor(ctx context.Context, in *UpsertAnchorRequest, opts ...grpc.CallOption) (*UpsertAnchorResponse, error) {
	out := new(UpsertAnchorResponse)
	err := c.cc.Invoke(ctx, LinkService_UpsertAnchor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) DeleteAnchor(ctx context.Context, in *DeleteAnchorRequest, opts ...grpc.CallOption) (*DeleteAnchorResponse, error) {
	out := new(DeleteAnchorResponse)
	err := c.cc.Invoke(ctx, LinkService_DeleteAnchor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) GetAnchor(ctx context.Context, in *GetAnchorRequest, opts ...grpc.CallOption) (*GetAnchorResponse, error) {
	out := new(GetAnchorResponse)
	err := c.cc.Invoke(ctx, LinkService_GetAnchor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) ListAnchors(ctx context.Context, in *ListAnchorsRequest, opts ...grpc.CallOption) (*ListAnchorsResponse, error) {
	out := new(ListAnchorsResponse)
	err := c.cc.Invoke(ctx, LinkService_ListAnchors_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) UpsertBacklink(ctx context.Context, in *UpsertBacklinkRequest, opts ...grpc.CallOption) (*UpsertBacklinkResponse, error) {
	out := new(UpsertBacklinkResponse)
	err := c.cc.Invoke(ctx, LinkService_UpsertBacklink_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) DeleteBacklink(ctx context.Context, in *DeleteBacklinkRequest, opts ...grpc.CallOption) (*DeleteBacklinkResponse, error) {
	out := new(DeleteBacklinkResponse)
	err := c.cc.Invoke(ctx, LinkService_DeleteBacklink_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) ListBacklinks(ctx context.Context, in *ListBacklinksRequest, opts ...grpc.CallOption) (*ListBacklinksResponse, error) {
	out := new(ListBacklinksResponse)
	err := c.cc.Invoke(ctx, LinkService_ListBacklinks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) ListOutboundLinks(ctx context.Context, in *ListOutboundLinksRequest, opts ...grpc.CallOption) (*ListOutboundLinksResponse, error) {
	out := new(ListOutboundLinksResponse)
	err := c.cc.Invoke(ctx, LinkService_ListOutboundLinks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) GetReferrers(ctx context.Context, in *GetReferrersRequest, opts ...grpc.CallOption) (*GetReferrersResponse, error) {
	out := new(GetReferrersResponse)
	err := c.cc.Invoke(ctx, LinkService_GetReferrers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) RecentBacklinks(ctx context.Context, in *RecentBacklinksRequest, opts ...grpc.CallOption) (*RecentBacklinksResponse, error) {
	out := new(RecentBacklinksResponse)
	err := c.cc.Invoke(ctx, LinkService_RecentBacklinks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) UpsertExternalLink(ctx context.Context, in *UpsertExternalLinkRequest, opts ...grpc.CallOption) (*UpsertExternalLinkResponse, error) {
	out := new(UpsertExternalLinkResponse)
	err := c.cc.Invoke(ctx, LinkService_UpsertExternalLink_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) DeleteExternalLink(ctx context.Context, in *DeleteExternalLinkRequest, opts ...grpc.CallOption) (*DeleteExternalLinkResponse, error) {
	out := new(DeleteExternalLinkResponse)
	err := c.cc.Invoke(ctx, LinkService_DeleteExternalLink_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkServiceClient) ListExternalLinks(ctx context.Context, in *ListExternalLinksRequest, opts ...grpc.CallOption) (*ListExternalLinksResponse, error) {
	out := new(ListExternalLinksResponse)
	err := c.cc.Invoke(ctx, LinkService_ListExternalLinks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkServiceServer is the server API for LinkService service.
// All implementations must embed UnimplementedLinkServiceServer
// for forward compatibility
type LinkServiceServer interface {
	// UpsertAnchor inserts or updates an anchor in the server-side index.
	UpsertAnchor(context.Context, *UpsertAnchorRequest) (*UpsertAnchorResponse, error)
	// DeleteAnchor removes an anchor. When tombstone=true the anchor is marked
	// deprecated instead of deleted, preserving referrer awareness.
	DeleteAnchor(context.Context, *DeleteAnchorRequest) (*DeleteAnchorResponse, error)
	// GetAnchor retrieves a single anchor by note URN and anchor ID.
	GetAnchor(context.Context, *GetAnchorRequest) (*GetAnchorResponse, error)
	// ListAnchors returns all anchors declared in a note, ordered by line ASC.
	ListAnchors(context.Context, *ListAnchorsRequest) (*ListAnchorsResponse, error)
	// UpsertBacklink inserts or updates a backlink record.
	UpsertBacklink(context.Context, *UpsertBacklinkRequest) (*UpsertBacklinkResponse, error)
	// DeleteBacklink removes a specific backlink record.
	DeleteBacklink(context.Context, *DeleteBacklinkRequest) (*DeleteBacklinkResponse, error)
	// ListBacklinks returns inbound backlinks for a note (optionally filtered by anchor).
	ListBacklinks(context.Context, *ListBacklinksRequest) (*ListBacklinksResponse, error)
	// ListOutboundLinks returns all outbound backlink records from a source note.
	ListOutboundLinks(context.Context, *ListOutboundLinksRequest) (*ListOutboundLinksResponse, error)
	// GetReferrers returns the URNs of all notes that link to a specific anchor.
	GetReferrers(context.Context, *GetReferrersRequest) (*GetReferrersResponse, error)
	// RecentBacklinks returns the most recently created backlinks across all notes,
	// with optional filtering. Used for browse/admin views.
	RecentBacklinks(context.Context, *RecentBacklinksRequest) (*RecentBacklinksResponse, error)
	// UpsertExternalLink inserts or updates an external link record.
	UpsertExternalLink(context.Context, *UpsertExternalLinkRequest) (*UpsertExternalLinkResponse, error)
	// DeleteExternalLink removes an external link record.
	DeleteExternalLink(context.Context, *DeleteExternalLinkRequest) (*DeleteExternalLinkResponse, error)
	// ListExternalLinks returns all external links from a source note.
	ListExternalLinks(context.Context, *ListExternalLinksRequest) (*ListExternalLinksResponse, error)
	mustEmbedUnimplementedLinkServiceServer()
}

// UnimplementedLinkServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLinkServiceServer struct {
}

func (UnimplementedLinkServiceServer) UpsertAnchor(context.Context, *UpsertAnchorRequest) (*UpsertAnchorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertAnchor not implemented")
}
func (UnimplementedLinkServiceServer) DeleteAnchor(context.Context, *DeleteAnchorRequest) (*DeleteAnchorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAnchor not implemented")
}
func (UnimplementedLinkServiceServer) GetAnchor(context.Context, *GetAnchorRequest) (*GetAnchorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnchor not implemented")
}
func (UnimplementedLinkServiceServer) ListAnchors(context.Context, *ListAnchorsRequest) (*ListAnchorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAnchors not implemented")
}
func (UnimplementedLinkServiceServer) UpsertBacklink(context.Context, *UpsertBacklinkRequest) (*UpsertBacklinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertBacklink not implemented")
}
func (UnimplementedLinkServiceServer) DeleteBacklink(context.Context, *DeleteBacklinkRequest) (*DeleteBacklinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBacklink not implemented")
}
func (UnimplementedLinkServiceServer) ListBacklinks(context.Context, *ListBacklinksRequest) (*ListBacklinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBacklinks not implemented")
}
func (UnimplementedLinkServiceServer) ListOutboundLinks(context.Context, *ListOutboundLinksRequest) (*ListOutboundLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOutboundLinks not implemented")
}
func (UnimplementedLinkServiceServer) GetReferrers(context.Context, *GetReferrersRequest) (*GetReferrersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReferrers not implemented")
}
func (UnimplementedLinkServiceServer) RecentBacklinks(context.Context, *RecentBacklinksRequest) (*RecentBacklinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecentBacklinks not implemented")
}
func (UnimplementedLinkServiceServer) UpsertExternalLink(context.Context, *UpsertExternalLinkRequest) (*UpsertExternalLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertExternalLink not implemented")
}
func (UnimplementedLinkServiceServer) DeleteExternalLink(context.Context, *DeleteExternalLinkRequest) (*DeleteExternalLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExternalLink not implemented")
}
func (UnimplementedLinkServiceServer) ListExternalLinks(context.Context, *ListExternalLinksRequest) (*ListExternalLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExternalLinks not implemented")
}
func (UnimplementedLinkServiceServer) mustEmbedUnimplementedLinkServiceServer() {}

// UnsafeLinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkServiceServer will
// result in compilation errors.
type UnsafeLinkServiceServer interface {
	mustEmbedUnimplementedLinkServiceServer()
}

func RegisterLinkServiceServer(s grpc.ServiceRegistrar, srv LinkServiceServer) {
	s.RegisterService(&LinkService_ServiceDesc, srv)
}

func _LinkService_UpsertAnchor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertAnchorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).UpsertAnchor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_UpsertAnchor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).UpsertAnchor(ctx, req.(*UpsertAnchorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_DeleteAnchor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAnchorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).DeleteAnchor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_DeleteAnchor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).DeleteAnchor(ctx, req.(*DeleteAnchorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_GetAnchor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnchorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).GetAnchor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_GetAnchor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).GetAnchor(ctx, req.(*GetAnchorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_ListAnchors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAnchorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).ListAnchors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_ListAnchors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).ListAnchors(ctx, req.(*ListAnchorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_UpsertBacklink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertBacklinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).UpsertBacklink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_UpsertBacklink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).UpsertBacklink(ctx, req.(*UpsertBacklinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_DeleteBacklink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBacklinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).DeleteBacklink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_DeleteBacklink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).DeleteBacklink(ctx, req.(*DeleteBacklinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_ListBacklinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBacklinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).ListBacklinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_ListBacklinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).ListBacklinks(ctx, req.(*ListBacklinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_ListOutboundLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOutboundLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).ListOutboundLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_ListOutboundLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).ListOutboundLinks(ctx, req.(*ListOutboundLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_GetReferrers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReferrersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).GetReferrers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_GetReferrers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).GetReferrers(ctx, req.(*GetReferrersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_RecentBacklinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecentBacklinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).RecentBacklinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_RecentBacklinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).RecentBacklinks(ctx, req.(*RecentBacklinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_UpsertExternalLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertExternalLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).UpsertExternalLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_UpsertExternalLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).UpsertExternalLink(ctx, req.(*UpsertExternalLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_DeleteExternalLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExternalLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).DeleteExternalLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_DeleteExternalLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).DeleteExternalLink(ctx, req.(*DeleteExternalLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkService_ListExternalLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExternalLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServiceServer).ListExternalLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkService_ListExternalLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServiceServer).ListExternalLinks(ctx, req.(*ListExternalLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LinkService_ServiceDesc is the grpc.ServiceDesc for LinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notx.v1.LinkService",
	HandlerType: (*LinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertAnchor",
			Handler:    _LinkService_UpsertAnchor_Handler,
		},
		{
			MethodName: "DeleteAnchor",
			Handler:    _LinkService_DeleteAnchor_Handler,
		},
		{
			MethodName: "GetAnchor",
			Handler:    _LinkService_GetAnchor_Handler,
		},
		{
			MethodName: "ListAnchors",
			Handler:    _LinkService_ListAnchors_Handler,
		},
		{
			MethodName: "UpsertBacklink",
			Handler:    _LinkService_UpsertBacklink_Handler,
		},
		{
			MethodName: "DeleteBacklink",
			Handler:    _LinkService_DeleteBacklink_Handler,
		},
		{
			MethodName: "ListBacklinks",
			Handler:    _LinkService_ListBacklinks_Handler,
		},
		{
			MethodName: "ListOutboundLinks",
			Handler:    _LinkService_ListOutboundLinks_Handler,
		},
		{
			MethodName: "GetReferrers",
			Handler:    _LinkService_GetReferrers_Handler,
		},
		{
			MethodName: "RecentBacklinks",
			Handler:    _LinkService_RecentBacklinks_Handler,
		},
		{
			MethodName: "UpsertExternalLink",
			Handler:    _LinkService_UpsertExternalLink_Handler,
		},
		{
			MethodName: "DeleteExternalLink",
			Handler:    _LinkService_DeleteExternalLink_Handler,
		},
		{
			MethodName: "ListExternalLinks",
			Handler:    _LinkService_ListExternalLinks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "link.proto",
}
