// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: link.proto

package notxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnchorRecord is the server-side representation of a declared anchor in a note.
// Anchors are the stable link targets that external notes reference.
type AnchorRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteUrn   string                 `protobuf:"bytes,1,opt,name=note_urn,json=noteUrn,proto3" json:"note_urn,omitempty"`
	AnchorId  string                 `protobuf:"bytes,2,opt,name=anchor_id,json=anchorId,proto3" json:"anchor_id,omitempty"`
	Line      int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	CharStart int32                  `protobuf:"varint,4,opt,name=char_start,json=charStart,proto3" json:"char_start,omitempty"`
	CharEnd   int32                  `protobuf:"varint,5,opt,name=char_end,json=charEnd,proto3" json:"char_end,omitempty"`
	Preview   string                 `protobuf:"bytes,6,opt,name=preview,proto3" json:"preview,omitempty"`
	Status    string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "ok" | "broken" | "deprecated"
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *AnchorRecord) Reset() {
	*x = AnchorRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnchorRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorRecord) ProtoMessage() {}

func (x *AnchorRecord) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorRecord.ProtoReflect.Descriptor instead.
func (*AnchorRecord) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{0}
}

func (x *AnchorRecord) GetNoteUrn() string {
	if x != nil {
		return x.NoteUrn
	}
	return ""
}

func (x *AnchorRecord) GetAnchorId() string {
	if x != nil {
		return x.AnchorId
	}
	return ""
}

func (x *AnchorRecord) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *AnchorRecord) GetCharStart() int32 {
	if x != nil {
		return x.CharStart
	}
	return 0
}

func (x *AnchorRecord) GetCharEnd() int32 {
	if x != nil {
		return x.CharEnd
	}
	return 0
}

func (x *AnchorRecord) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

func (x *AnchorRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnchorRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// BacklinkRecord is a single inbound link entry in the backlink index.
// It records that source_urn links into target_urn at target_anchor.
type BacklinkRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceUrn    string                 `protobuf:"bytes,1,opt,name=source_urn,json=sourceUrn,proto3" json:"source_urn,omitempty"`
	TargetUrn    string                 `protobuf:"bytes,2,opt,name=target_urn,json=targetUrn,proto3" json:"target_urn,omitempty"`
	TargetAnchor string                 `protobuf:"bytes,3,opt,name=target_anchor,json=targetAnchor,proto3" json:"target_anchor,omitempty"`
	Label        string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *BacklinkRecord) Reset() {
	*x = BacklinkRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BacklinkRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacklinkRecord) ProtoMessage() {}

func (x *BacklinkRecord) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacklinkRecord.ProtoReflect.Descriptor instead.
func (*BacklinkRecord) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{1}
}

func (x *BacklinkRecord) GetSourceUrn() string {
	if x != nil {
		return x.SourceUrn
	}
	return ""
}

func (x *BacklinkRecord) GetTargetUrn() string {
	if x != nil {
		return x.TargetUrn
	}
	return ""
}

func (x *BacklinkRecord) GetTargetAnchor() string {
	if x != nil {
		return x.TargetAnchor
	}
	return ""
}

func (x *BacklinkRecord) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BacklinkRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ExternalLinkRecord is an outbound link from a note to an external URI.
type ExternalLinkRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceUrn string                 `protobuf:"bytes,1,opt,name=source_urn,json=sourceUrn,proto3" json:"source_urn,omitempty"`
	Uri       string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Label     string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *ExternalLinkRecord) Reset() {
	*x = ExternalLinkRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalLinkRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalLinkRecord) ProtoMessage() {}

func (x *ExternalLinkRecord) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalLinkRecord.ProtoReflect.Descriptor instead.
func (*ExternalLinkRecord) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{2}
}

func (x *ExternalLinkRecord) GetSourceUrn() string {
	if x != nil {
		return x.SourceUrn
	}
	return ""
}

func (x *ExternalLinkRecord) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ExternalLinkRecord) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ExternalLinkRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UpsertAnchorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteUrn   string `protobuf:"bytes,1,opt,name=note_urn,json=noteUrn,proto3" json:"note_urn,omitempty"`
	AnchorId  string `protobuf:"bytes,2,opt,name=anchor_id,json=anchorId,proto3" json:"anchor_id,omitempty"`
	Line      int32  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	CharStart int32  `protobuf:"varint,4,opt,name=char_start,json=charStart,proto3" json:"char_start,omitempty"`
	CharEnd   int32  `protobuf:"varint,5,opt,name=char_end,json=charEnd,proto3" json:"char_end,omitempty"`
	Preview   string `protobuf:"bytes,6,opt,name=preview,proto3" json:"preview,omitempty"`
	Status    string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // defaults to "ok" when empty
}

func (x *UpsertAnchorRequest) Reset() {
	*x = UpsertAnchorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertAnchorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAnchorRequest) ProtoMessage() {}

func (x *UpsertAnchorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAnchorRequest.ProtoReflect.Descriptor instead.
func (*UpsertAnchorRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertAnchorRequest) GetNoteUrn() string {
	if x != nil {
		return x.NoteUrn
	}
	return ""
}

func (x *UpsertAnchorRequest) GetAnchorId() string {
	if x != nil {
		return x.AnchorId
	}
	return ""
}

func (x *UpsertAnchorRequest) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *UpsertAnchorRequest) GetCharStart() int32 {
	if x != nil {
		return x.CharStart
	}
	return 0
}

func (x *UpsertAnchorRequest) GetCharEnd() int32 {
	if x != nil {
		return x.CharEnd
	}
	return 0
}

func (x *UpsertAnchorRequest) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

func (x *UpsertAnchorRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpsertAnchorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Anchor *AnchorRecord `protobuf:"bytes,1,opt,name=anchor,proto3" json:"anchor,omitempty"`
}

func (x *UpsertAnchorResponse) Reset() {
	*x = UpsertAnchorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertAnchorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAnchorResponse) ProtoMessage() {}

func (x *UpsertAnchorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAnchorResponse.ProtoReflect.Descriptor instead.
func (*UpsertAnchorResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertAnchorResponse) GetAnchor() *AnchorRecord {
	if x != nil {
		return x.Anchor
	}
	return nil
}

type DeleteAnchorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteUrn   string `protobuf:"bytes,1,opt,name=note_urn,json=noteUrn,proto3" json:"note_urn,omitempty"`
	AnchorId  string `protobuf:"bytes,2,opt,name=anchor_id,json=anchorId,proto3" json:"anchor_id,omitempty"`
	Tombstone bool   `protobuf:"varint,3,opt,name=tombstone,proto3" json:"tombstone,omitempty"` // when true: mark deprecated instead of deleting
}

func (x *DeleteAnchorRequest) Reset() {
	*x = DeleteAnchorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAnchorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnchorRequest) ProtoMessage() {}

func (x *DeleteAnchorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnchorRequest.ProtoReflect.Descriptor instead.
func (*DeleteAnchorRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAnchorRequest) GetNoteUrn() string {
	if x != nil {
		return x.NoteUrn
	}
	return ""
}

func (x *DeleteAnchorRequest) GetAnchorId() string {
	if x != nil {
		return x.AnchorId
	}
	return ""
}

func (x *DeleteAnchorRequest) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

type DeleteAnchorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *DeleteAnchorResponse) Reset() {
	*x = DeleteAnchorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAnchorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnchorResponse) ProtoMessage() {}

func (x *DeleteAnchorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnchorResponse.ProtoReflect.Descriptor instead.
func (*DeleteAnchorResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAnchorResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GetAnchorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteUrn  string `protobuf:"bytes,1,opt,name=note_urn,json=noteUrn,proto3" json:"note_urn,omitempty"`
	AnchorId string `protobuf:"bytes,2,opt,name=anchor_id,json=anchorId,proto3" json:"anchor_id,omitempty"`
}

func (x *GetAnchorRequest) Reset() {
	*x = GetAnchorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnchorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnchorRequest) ProtoMessage() {}

func (x *GetAnchorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnchorRequest.ProtoReflect.Descriptor instead.
func (*GetAnchorRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{7}
}

func (x *GetAnchorRequest) GetNoteUrn() string {
	if x != nil {
		return x.NoteUrn
	}
	return ""
}

func (x *GetAnchorRequest) GetAnchorId() string {
	if x != nil {
		return x.AnchorId
	}
	return ""
}

type GetAnchorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Anchor *AnchorRecord `protobuf:"bytes,1,opt,name=anchor,proto3" json:"anchor,omitempty"`
}

func (x *GetAnchorResponse) Reset() {
	*x = GetAnchorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnchorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnchorResponse) ProtoMessage() {}

func (x *GetAnchorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnchorResponse.ProtoReflect.Descriptor instead.
func (*GetAnchorResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{8}
}

func (x *GetAnchorResponse) GetAnchor() *AnchorRecord {
	if x != nil {
		return x.Anchor
	}
	return nil
}

type ListAnchorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteUrn string `protobuf:"bytes,1,opt,name=note_urn,json=noteUrn,proto3" json:"note_urn,omitempty"`
}

func (x *ListAnchorsRequest) Reset() {
	*x = ListAnchorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAnchorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnchorsRequest) ProtoMessage() {}

func (x *ListAnchorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnchorsRequest.ProtoReflect.Descriptor instead.
func (*ListAnchorsRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{9}
}

func (x *ListAnchorsRequest) GetNoteUrn() string {
	if x != nil {
		return x.NoteUrn
	}
	return ""
}

type ListAnchorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Anchors []*AnchorRecord `protobuf:"bytes,1,rep,name=anchors,proto3" json:"anchors,omitempty"`
}

func (x *ListAnchorsResponse) Reset() {
	*x = ListAnchorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAnchorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnchorsResponse) ProtoMessage() {}

func (x *ListAnchorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnchorsResponse.ProtoReflect.Descriptor instead.
func (*ListAnchorsResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{10}
}

func (x *ListAnchorsResponse) GetAnchors() []*AnchorRecord {
	if x != nil {
		return x.Anchors
	}
	return nil
}

type UpsertBacklinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceUrn    string `protobuf:"bytes,1,opt,name=source_urn,json=sourceUrn,proto3" json:"source_urn,omitempty"`
	TargetUrn    string `protobuf:"bytes,2,opt,name=target_urn,json=targetUrn,proto3" json:"target_urn,omitempty"`
	TargetAnchor string `protobuf:"bytes,3,opt,name=target_anchor,json=targetAnchor,proto3" json:"target_anchor,omitempty"`
	Label        string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *UpsertBacklinkRequest) Reset() {
	*x = UpsertBacklinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertBacklinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertBacklinkRequest) ProtoMessage() {}

func (x *UpsertBacklinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertBacklinkRequest.ProtoReflect.Descriptor instead.
func (*UpsertBacklinkRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{11}
}

func (x *UpsertBacklinkRequest) GetSourceUrn() string {
	if x != nil {
		return x.SourceUrn
	}
	return ""
}

func (x *UpsertBacklinkRequest) GetTargetUrn() string {
	if x != nil {
		return x.TargetUrn
	}
	return ""
}

func (x *UpsertBacklinkRequest) GetTargetAnchor() string {
	if x != nil {
		return x.TargetAnchor
	}
	return ""
}

func (x *UpsertBacklinkRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type UpsertBacklinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backlink *BacklinkRecord `protobuf:"bytes,1,opt,name=backlink,proto3" json:"backlink,omitempty"`
}

func (x *UpsertBacklinkResponse) Reset() {
	*x = UpsertBacklinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertBacklinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertBacklinkResponse) ProtoMessage() {}

func (x *UpsertBacklinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertBacklinkResponse.ProtoReflect.Descriptor instead.
func (*UpsertBacklinkResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{12}
}

func (x *UpsertBacklinkResponse) GetBacklink() *BacklinkRecord {
	if x != nil {
		return x.Backlink
	}
	return nil
}

type DeleteBacklinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceUrn    string `protobuf:"bytes,1,opt,name=source_urn,json=sourceUrn,proto3" json:"source_urn,omitempty"`
	TargetUrn    string `protobuf:"bytes,2,opt,name=target_urn,json=targetUrn,proto3" json:"target_urn,omitempty"`
	TargetAnchor string `protobuf:"bytes,3,opt,name=target_anchor,json=targetAnchor,proto3" json:"target_anchor,omitempty"`
}

func (x *DeleteBacklinkRequest) Reset() {
	*x = DeleteBacklinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBacklinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBacklinkRequest) ProtoMessage() {}

func (x *DeleteBacklinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBacklinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteBacklinkRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteBacklinkRequest) GetSourceUrn() string {
	if x != nil {
		return x.SourceUrn
	}
	return ""
}

func (x *DeleteBacklinkRequest) GetTargetUrn() string {
	if x != nil {
		return x.TargetUrn
	}
	return ""
}

func (x *DeleteBacklinkRequest) GetTargetAnchor() string {
	if x != nil {
		return x.TargetAnchor
	}
	return ""
}

type DeleteBacklinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *DeleteBacklinkResponse) Reset() {
	*x = DeleteBacklinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBacklinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBacklinkResponse) ProtoMessage() {}

func (x *DeleteBacklinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBacklinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteBacklinkResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteBacklinkResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ListBacklinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetUrn string `protobuf:"bytes,1,opt,name=target_urn,json=targetUrn,proto3" json:"target_urn,omitempty"` // required
	AnchorId  string `protobuf:"bytes,2,opt,name=anchor_id,json=anchorId,proto3" json:"anchor_id,omitempty"`    // optional filter
}

func (x *ListBacklinksRequest) Reset() {
	*x = ListBacklinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBacklinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBacklinksRequest) ProtoMessage() {}

func (x *ListBacklinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBacklinksRequest.ProtoReflect.Descriptor instead.
func (*ListBacklinksRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{15}
}

func (x *ListBacklinksRequest) GetTargetUrn() string {
	if x != nil {
		return x.TargetUrn
	}
	return ""
}

func (x *ListBacklinksRequest) GetAnchorId() string {
	if x != nil {
		return x.AnchorId
	}
	return ""
}

type ListBacklinksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backlinks []*BacklinkRecord `protobuf:"bytes,1,rep,name=backlinks,proto3" json:"backlinks,omitempty"`
}

func (x *ListBacklinksResponse) Reset() {
	*x = ListBacklinksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBacklinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBacklinksResponse) ProtoMessage() {}

func (x *ListBacklinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBacklinksResponse.ProtoReflect.Descriptor instead.
func (*ListBacklinksResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{16}
}

func (x *ListBacklinksResponse) GetBacklinks() []*BacklinkRecord {
	if x != nil {
		return x.Backlinks
	}
	return nil
}

type ListOutboundLinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceUrn string `protobuf:"bytes,1,opt,name=source_urn,json=sourceUrn,proto3" json:"source_urn,omitempty"` // required
}

func (x *ListOutboundLinksRequest) Reset() {
	*x = ListOutboundLinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOutboundLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutboundLinksRequest) ProtoMessage() {}

func (x *ListOutboundLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutboundLinksRequest.ProtoReflect.Descriptor instead.
func (*ListOutboundLinksRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{17}
}

func (x *ListOutboundLinksRequest) GetSourceUrn() string {
	if x != nil {
		return x.SourceUrn
	}
	return ""
}

type ListOutboundLinksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Links []*BacklinkRecord `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
}

func (x *ListOutboundLinksResponse) Reset() {
	*x = ListOutboundLinksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOutboundLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutboundLinksResponse) ProtoMessage() {}

func (x *ListOutboundLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutboundLinksResponse.ProtoReflect.Descriptor instead.
func (*ListOutboundLinksResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{18}
}

func (x *ListOutboundLinksResponse) GetLinks() []*BacklinkRecord {
	if x != nil {
		return x.Links
	}
	return nil
}

type GetReferrersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetUrn string `protobuf:"bytes,1,opt,name=target_urn,json=targetUrn,proto3" json:"target_urn,omitempty"`
	AnchorId  string `protobuf:"bytes,2,opt,name=anchor_id,json=anchorId,proto3" json:"anchor_id,omitempty"`
}

func (x *GetReferrersRequest) Reset() {
	*x = GetReferrersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReferrersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferrersRequest) ProtoMessage() {}

func (x *GetReferrersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferrersRequest.ProtoReflect.Descriptor instead.
func (*GetReferrersRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{19}
}

func (x *GetReferrersRequest) GetTargetUrn() string {
	if x != nil {
		return x.TargetUrn
	}
	return ""
}

func (x *GetReferrersRequest) GetAnchorId() string {
	if x != nil {
		return x.AnchorId
	}
	return ""
}

type GetReferrersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceUrns []string `protobuf:"bytes,1,rep,name=source_urns,json=sourceUrns,proto3" json:"source_urns,omitempty"`
}

func (x *GetReferrersResponse) Reset() {
	*x = GetReferrersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReferrersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferrersResponse) ProtoMessage() {}

func (x *GetReferrersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferrersResponse.ProtoReflect.Descriptor instead.
func (*GetReferrersResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{20}
}

func (x *GetReferrersResponse) GetSourceUrns() []string {
	if x != nil {
		return x.SourceUrns
	}
	return nil
}

type UpsertExternalLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceUrn string `protobuf:"bytes,1,opt,name=source_urn,json=sourceUrn,proto3" json:"source_urn,omitempty"`
	Uri       string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Label     string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *UpsertExternalLinkRequest) Reset() {
	*x = UpsertExternalLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertExternalLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertExternalLinkRequest) ProtoMessage() {}

func (x *UpsertExternalLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertExternalLinkRequest.ProtoReflect.Descriptor instead.
func (*UpsertExternalLinkRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{21}
}

func (x *UpsertExternalLinkRequest) GetSourceUrn() string {
	if x != nil {
		return x.SourceUrn
	}
	return ""
}

func (x *UpsertExternalLinkRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *UpsertExternalLinkRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type UpsertExternalLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link *ExternalLinkRecord `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *UpsertExternalLinkResponse) Reset() {
	*x = UpsertExternalLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertExternalLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertExternalLinkResponse) ProtoMessage() {}

func (x *UpsertExternalLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertExternalLinkResponse.ProtoReflect.Descriptor instead.
func (*UpsertExternalLinkResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{22}
}

func (x *UpsertExternalLinkResponse) GetLink() *ExternalLinkRecord {
	if x != nil {
		return x.Link
	}
	return nil
}

type DeleteExternalLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceUrn string `protobuf:"bytes,1,opt,name=source_urn,json=sourceUrn,proto3" json:"source_urn,omitempty"`
	Uri       string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *DeleteExternalLinkRequest) Reset() {
	*x = DeleteExternalLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteExternalLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExternalLinkRequest) ProtoMessage() {}

func (x *DeleteExternalLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExternalLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteExternalLinkRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteExternalLinkRequest) GetSourceUrn() string {
	if x != nil {
		return x.SourceUrn
	}
	return ""
}

func (x *DeleteExternalLinkRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type DeleteExternalLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *DeleteExternalLinkResponse) Reset() {
	*x = DeleteExternalLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteExternalLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExternalLinkResponse) ProtoMessage() {}

func (x *DeleteExternalLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExternalLinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteExternalLinkResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteExternalLinkResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ListExternalLinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceUrn string `protobuf:"bytes,1,opt,name=source_urn,json=sourceUrn,proto3" json:"source_urn,omitempty"` // required
}

func (x *ListExternalLinksRequest) Reset() {
	*x = ListExternalLinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListExternalLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalLinksRequest) ProtoMessage() {}

func (x *ListExternalLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalLinksRequest.ProtoReflect.Descriptor instead.
func (*ListExternalLinksRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{25}
}

func (x *ListExternalLinksRequest) GetSourceUrn() string {
	if x != nil {
		return x.SourceUrn
	}
	return ""
}

type ListExternalLinksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Links []*ExternalLinkRecord `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
}

func (x *ListExternalLinksResponse) Reset() {
	*x = ListExternalLinksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListExternalLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalLinksResponse) ProtoMessage() {}

func (x *ListExternalLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalLinksResponse.ProtoReflect.Descriptor instead.
func (*ListExternalLinksResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{26}
}

func (x *ListExternalLinksResponse) GetLinks() []*ExternalLinkRecord {
	if x != nil {
		return x.Links
	}
	return nil
}

type RecentBacklinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional. Filter where source_urn OR target_urn matches this value.
	NoteUrn string `protobuf:"bytes,1,opt,name=note_urn,json=noteUrn,proto3" json:"note_urn,omitempty"`
	// Optional. Substring filter on label (case-insensitive).
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// Max results to return. 0 = server default (50). Max 200.
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *RecentBacklinksRequest) Reset() {
	*x = RecentBacklinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecentBacklinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentBacklinksRequest) ProtoMessage() {}

func (x *RecentBacklinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentBacklinksRequest.ProtoReflect.Descriptor instead.
func (*RecentBacklinksRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{27}
}

func (x *RecentBacklinksRequest) GetNoteUrn() string {
	if x != nil {
		return x.NoteUrn
	}
	return ""
}

func (x *RecentBacklinksRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RecentBacklinksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecentBacklinksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backlinks []*BacklinkRecord `protobuf:"bytes,1,rep,name=backlinks,proto3" json:"backlinks,omitempty"`
}

func (x *RecentBacklinksResponse) Reset() {
	*x = RecentBacklinksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecentBacklinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentBacklinksResponse) ProtoMessage() {}

func (x *RecentBacklinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentBacklinksResponse.ProtoReflect.Descriptor instead.
func (*RecentBacklinksResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{28}
}

func (x *RecentBacklinksResponse) GetBacklinks() []*BacklinkRecord {
	if x != nil {
		return x.Backlinks
	}
	return nil
}

var File_link_proto protoreflect.FileDescriptor

var file_link_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6e, 0x6f,
	0x74, 0x78, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x02, 0x0a, 0x0c, 0x41, 0x6e, 0x63, 0x68, 0x6f,
	0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x74, 0x65, 0x5f,
	0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x55,
	0x72, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c,
	0x69, 0x6e, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x72, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x72, 0x45, 0x6e, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xc4, 0x01, 0x0a, 0x0e, 0x42,
	0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6e, 0x12, 0x1d, 0x0a, 0x0a,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x72, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x96, 0x01, 0x0a, 0x12, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69,
	0x6e, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12,
	0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xcd, 0x01, 0x0a, 0x13, 0x55,
	0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x55, 0x72, 0x6e, 0x12, 0x1b, 0x0a,
	0x09, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69,
	0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x63, 0x68, 0x61, 0x72, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x63, 0x68, 0x61, 0x72, 0x45, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x45, 0x0a, 0x14, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x63,
	0x68, 0x6f, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x61, 0x6e, 0x63, 0x68, 0x6f,
	0x72, 0x22, 0x6b, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6e, 0x63, 0x68, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x74, 0x65,
	0x5f, 0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x74, 0x65,
	0x55, 0x72, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x6d, 0x62, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x6f, 0x6d, 0x62, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x22, 0x30,
	0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x22, 0x4a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x75, 0x72, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x55, 0x72, 0x6e, 0x12,
	0x1b, 0x0a, 0x09, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2d, 0x0a, 0x06, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x63, 0x68,
	0x6f, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72,
	0x22, 0x2f, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x75,
	0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x55, 0x72,
	0x6e, 0x22, 0x46, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x61, 0x6e, 0x63, 0x68,
	0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6e, 0x6f, 0x74, 0x78,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x07, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x15, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x72,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55,
	0x72, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x72, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x72,
	0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x6e, 0x63, 0x68,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x4d, 0x0a, 0x16,
	0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x6c, 0x69,
	0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x7a, 0x0a, 0x15, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75,
	0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x55, 0x72, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x72,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55,
	0x72, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x6e, 0x63,
	0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x22, 0x32, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x52, 0x0a, 0x14, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x72,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55,
	0x72, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x22,
	0x4e, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x09, 0x62, 0x61, 0x63, 0x6b,
	0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6e, 0x6f,
	0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x09, 0x62, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x22,
	0x39, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x4c,
	0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6e, 0x22, 0x4a, 0x0a, 0x19, 0x4c, 0x69,
	0x73, 0x74, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31,
	0x2e, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x51, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x72, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x72, 0x6e, 0x12, 0x1b, 0x0a, 0x09,
	0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72,
	0x6e, 0x73, 0x22, 0x62, 0x0a, 0x19, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x4d, 0x0a, 0x1a, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x4c, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x69, 0x22, 0x36, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x39, 0x0a, 0x18, 0x4c,
	0x69, 0x73, 0x74, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x55, 0x72, 0x6e, 0x22, 0x4e, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x5f, 0x0a, 0x16, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74,
	0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x55, 0x72, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x50, 0x0a, 0x17, 0x52, 0x65, 0x63, 0x65, 0x6e,
	0x74, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x35, 0x0a, 0x09, 0x62, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e,
	0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x09,
	0x62, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x32, 0xc4, 0x08, 0x0a, 0x0b, 0x4c, 0x69,
	0x6e, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x55, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x12, 0x1c, 0x2e, 0x6e, 0x6f, 0x74, 0x78,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x12, 0x1c, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72,
	0x12, 0x19, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e,
	0x63, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6e, 0x6f,
	0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73, 0x12, 0x1b, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x51, 0x0a, 0x0e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x6c,
	0x69, 0x6e, 0x6b, 0x12, 0x1e, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61,
	0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x1e, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x42,
	0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x1d, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x21, 0x2e, 0x6e,
	0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x75, 0x74, 0x62, 0x6f,
	0x75, 0x6e, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x75,
	0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x72,
	0x65, 0x72, 0x73, 0x12, 0x1c, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x54, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69,
	0x6e, 0x6b, 0x73, 0x12, 0x1f, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x63, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x63, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x12, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x22, 0x2e, 0x6e,
	0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x45, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72,
	0x74, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x22, 0x2e, 0x6e, 0x6f,
	0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x21, 0x2e, 0x6e, 0x6f, 0x74, 0x78,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6e,
	0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a,
	0x65, 0x62, 0x61, 0x71, 0x75, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x78, 0x2d, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6e, 0x6f, 0x74, 0x78, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_link_proto_rawDescOnce sync.Once
	file_link_proto_rawDescData = file_link_proto_rawDesc
)

func file_link_proto_rawDescGZIP() []byte {
	file_link_proto_rawDescOnce.Do(func() {
		file_link_proto_rawDescData = protoimpl.X.CompressGZIP(file_link_proto_rawDescData)
	})
	return file_link_proto_rawDescData
}

var file_link_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_link_proto_goTypes = []interface{}{
	(*AnchorRecord)(nil),               // 0: notx.v1.AnchorRecord
	(*BacklinkRecord)(nil),             // 1: notx.v1.BacklinkRecord
	(*ExternalLinkRecord)(nil),         // 2: notx.v1.ExternalLinkRecord
	(*UpsertAnchorRequest)(nil),        // 3: notx.v1.UpsertAnchorRequest
	(*UpsertAnchorResponse)(nil),       // 4: notx.v1.UpsertAnchorResponse
	(*DeleteAnchorRequest)(nil),        // 5: notx.v1.DeleteAnchorRequest
	(*DeleteAnchorResponse)(nil),       // 6: notx.v1.DeleteAnchorResponse
	(*GetAnchorRequest)(nil),           // 7: notx.v1.GetAnchorRequest
	(*GetAnchorResponse)(nil),          // 8: notx.v1.GetAnchorResponse
	(*ListAnchorsRequest)(nil),         // 9: notx.v1.ListAnchorsRequest
	(*ListAnchorsResponse)(nil),        // 10: notx.v1.ListAnchorsResponse
	(*UpsertBacklinkRequest)(nil),      // 11: notx.v1.UpsertBacklinkRequest
	(*UpsertBacklinkResponse)(nil),     // 12: notx.v1.UpsertBacklinkResponse
	(*DeleteBacklinkRequest)(nil),      // 13: notx.v1.DeleteBacklinkRequest
	(*DeleteBacklinkResponse)(nil),     // 14: notx.v1.DeleteBacklinkResponse
	(*ListBacklinksRequest)(nil),       // 15: notx.v1.ListBacklinksRequest
	(*ListBacklinksResponse)(nil),      // 16: notx.v1.ListBacklinksResponse
	(*ListOutboundLinksRequest)(nil),   // 17: notx.v1.ListOutboundLinksRequest
	(*ListOutboundLinksResponse)(nil),  // 18: notx.v1.ListOutboundLinksResponse
	(*GetReferrersRequest)(nil),        // 19: notx.v1.GetReferrersRequest
	(*GetReferrersResponse)(nil),       // 20: notx.v1.GetReferrersResponse
	(*UpsertExternalLinkRequest)(nil),  // 21: notx.v1.UpsertExternalLinkRequest
	(*UpsertExternalLinkResponse)(nil), // 22: notx.v1.UpsertExternalLinkResponse
	(*DeleteExternalLinkRequest)(nil),  // 23: notx.v1.DeleteExternalLinkRequest
	(*DeleteExternalLinkResponse)(nil), // 24: notx.v1.DeleteExternalLinkResponse
	(*ListExternalLinksRequest)(nil),   // 25: notx.v1.ListExternalLinksRequest
	(*ListExternalLinksResponse)(nil),  // 26: notx.v1.ListExternalLinksResponse
	(*RecentBacklinksRequest)(nil),     // 27: notx.v1.RecentBacklinksRequest
	(*RecentBacklinksResponse)(nil),    // 28: notx.v1.RecentBacklinksResponse
	(*timestamppb.Timestamp)(nil),      // 29: google.protobuf.Timestamp
}
var file_link_proto_depIdxs = []int32{
	29, // 0: notx.v1.AnchorRecord.updated_at:type_name -> google.protobuf.Timestamp
	29, // 1: notx.v1.BacklinkRecord.created_at:type_name -> google.protobuf.Timestamp
	29, // 2: notx.v1.ExternalLinkRecord.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: notx.v1.UpsertAnchorResponse.anchor:type_name -> notx.v1.AnchorRecord
	0,  // 4: notx.v1.GetAnchorResponse.anchor:type_name -> notx.v1.AnchorRecord
	0,  // 5: notx.v1.ListAnchorsResponse.anchors:type_name -> notx.v1.AnchorRecord
	1,  // 6: notx.v1.UpsertBacklinkResponse.backlink:type_name -> notx.v1.BacklinkRecord
	1,  // 7: notx.v1.ListBacklinksResponse.backlinks:type_name -> notx.v1.BacklinkRecord
	1,  // 8: notx.v1.ListOutboundLinksResponse.links:type_name -> notx.v1.BacklinkRecord
	2,  // 9: notx.v1.UpsertExternalLinkResponse.link:type_name -> notx.v1.ExternalLinkRecord
	2,  // 10: notx.v1.ListExternalLinksResponse.links:type_name -> notx.v1.ExternalLinkRecord
	1,  // 11: notx.v1.RecentBacklinksResponse.backlinks:type_name -> notx.v1.BacklinkRecord
	3,  // 12: notx.v1.LinkService.UpsertAnchor:input_type -> notx.v1.UpsertAnchorRequest
	5,  // 13: notx.v1.LinkService.DeleteAnchor:input_type -> notx.v1.DeleteAnchorRequest
	7,  // 14: notx.v1.LinkService.GetAnchor:input_type -> notx.v1.GetAnchorRequest
	9,  // 15: notx.v1.LinkService.ListAnchors:input_type -> notx.v1.ListAnchorsRequest
	11, // 16: notx.v1.LinkService.UpsertBacklink:input_type -> notx.v1.UpsertBacklinkRequest
	13, // 17: notx.v1.LinkService.DeleteBacklink:input_type -> notx.v1.DeleteBacklinkRequest
	15, // 18: notx.v1.LinkService.ListBacklinks:input_type -> notx.v1.ListBacklinksRequest
	17, // 19: notx.v1.LinkService.ListOutboundLinks:input_type -> notx.v1.ListOutboundLinksRequest
	19, // 20: notx.v1.LinkService.GetReferrers:input_type -> notx.v1.GetReferrersRequest
	27, // 21: notx.v1.LinkService.RecentBacklinks:input_type -> notx.v1.RecentBacklinksRequest
	21, // 22: notx.v1.LinkService.UpsertExternalLink:input_type -> notx.v1.UpsertExternalLinkRequest
	23, // 23: notx.v1.LinkService.DeleteExternalLink:input_type -> notx.v1.DeleteExternalLinkRequest
	25, // 24: notx.v1.LinkService.ListExternalLinks:input_type -> notx.v1.ListExternalLinksRequest
	4,  // 25: notx.v1.LinkService.UpsertAnchor:output_type -> notx.v1.UpsertAnchorResponse
	6,  // 26: notx.v1.LinkService.DeleteAnchor:output_type -> notx.v1.DeleteAnchorResponse
	8,  // 27: notx.v1.LinkService.GetAnchor:output_type -> notx.v1.GetAnchorResponse
	10, // 28: notx.v1.LinkService.ListAnchors:output_type -> notx.v1.ListAnchorsResponse
	12, // 29: notx.v1.LinkService.UpsertBacklink:output_type -> notx.v1.UpsertBacklinkResponse
	14, // 30: notx.v1.LinkService.DeleteBacklink:output_type -> notx.v1.DeleteBacklinkResponse
	16, // 31: notx.v1.LinkService.ListBacklinks:output_type -> notx.v1.ListBacklinksResponse
	18, // 32: notx.v1.LinkService.ListOutboundLinks:output_type -> notx.v1.ListOutboundLinksResponse
	20, // 33: notx.v1.LinkService.GetReferrers:output_type -> notx.v1.GetReferrersResponse
	28, // 34: notx.v1.LinkService.RecentBacklinks:output_type -> notx.v1.RecentBacklinksResponse
	22, // 35: notx.v1.LinkService.UpsertExternalLink:output_type -> notx.v1.UpsertExternalLinkResponse
	24, // 36: notx.v1.LinkService.DeleteExternalLink:output_type -> notx.v1.DeleteExternalLinkResponse
	26, // 37: notx.v1.LinkService.ListExternalLinks:output_type -> notx.v1.ListExternalLinksResponse
	25, // [25:38] is the sub-list for method output_type
	12, // [12:25] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_link_proto_init() }
func file_link_proto_init() {
	if File_link_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_link_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnchorRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BacklinkRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalLinkRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertAnchorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertAnchorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAnchorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAnchorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnchorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnchorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAnchorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAnchorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertBacklinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertBacklinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBacklinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBacklinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBacklinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBacklinksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOutboundLinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOutboundLinksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReferrersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReferrersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertExternalLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertExternalLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteExternalLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteExternalLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListExternalLinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListExternalLinksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecentBacklinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecentBacklinksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_link_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_link_proto_goTypes,
		DependencyIndexes: file_link_proto_depIdxs,
		MessageInfos:      file_link_proto_msgTypes,
	}.Build()
	File_link_proto = out.File
	file_link_proto_rawDesc = nil
	file_link_proto_goTypes = nil
	file_link_proto_depIdxs = nil
}
