// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: note.proto

package notxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NoteService_GetNote_FullMethodName           = "/notx.v1.NoteService/GetNote"
	NoteService_ListNotes_FullMethodName         = "/notx.v1.NoteService/ListNotes"
	NoteService_CreateNote_FullMethodName        = "/notx.v1.NoteService/CreateNote"
	NoteService_UpdateNote_FullMethodName        = "/notx.v1.NoteService/UpdateNote"
	NoteService_DeleteNote_FullMethodName        = "/notx.v1.NoteService/DeleteNote"
	NoteService_AppendEvent_FullMethodName       = "/notx.v1.NoteService/AppendEvent"
	NoteService_StreamEvents_FullMethodName      = "/notx.v1.NoteService/StreamEvents"
	NoteService_SearchNotes_FullMethodName       = "/notx.v1.NoteService/SearchNotes"
	NoteService_ReplaceContent_FullMethodName    = "/notx.v1.NoteService/ReplaceContent"
	NoteService_ShareSecureNote_FullMethodName   = "/notx.v1.NoteService/ShareSecureNote"
	NoteService_ReceiveSharedNote_FullMethodName = "/notx.v1.NoteService/ReceiveSharedNote"
)

// NoteServiceClient is the client API for NoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoteServiceClient interface {
	// GetNote returns the full header + all events for a note.
	GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error)
	// ListNotes returns all note headers visible to the caller.
	ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error)
	// CreateNote registers a new note (header only; events follow via AppendEvent).
	CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error)
	// UpdateNote mutates mutable metadata fields on a note using a FieldMask
	// for partial update semantics.
	UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...grpc.CallOption) (*UpdateNoteResponse, error)
	// DeleteNote soft-deletes a note by URN.
	DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error)
	// AppendEvent appends a single event to an existing note.
	// For normal notes the server stores the plaintext entries and advances the
	// index. For secure notes it stores the encrypted blob verbatim.
	AppendEvent(ctx context.Context, in *AppendEventRequest, opts ...grpc.CallOption) (*AppendEventResponse, error)
	// StreamEvents opens a server-side stream that pushes all events for a note
	// starting from a given sequence number. Used by clients to catch up after
	// reconnect. For secure note events the server streams the encrypted blob
	// without decrypting it.
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (NoteService_StreamEventsClient, error)
	// SearchNotes performs a server-side full-text search over normal note
	// content. Secure notes are never included in results.
	SearchNotes(ctx context.Context, in *SearchNotesRequest, opts ...grpc.CallOption) (*SearchNotesResponse, error)
	// ReplaceContent atomically diffs the supplied plain-text content against the
	// note's current state and appends a single event capturing the delta.
	// Not permitted on secure notes.
	ReplaceContent(ctx context.Context, in *ReplaceContentRequest, opts ...grpc.CallOption) (*ReplaceContentResponse, error)
	// ShareSecureNote merges per-device wrapped Content Encryption Keys into
	// every stored Event for the note without ever seeing the plaintext CEK.
	ShareSecureNote(ctx context.Context, in *ShareSecureNoteRequest, opts ...grpc.CallOption) (*ShareSecureNoteResponse, error)
	// ReceiveSharedNote stores a note header and event stream forwarded from a
	// paired server. Idempotent: only events beyond the local head are written.
	ReceiveSharedNote(ctx context.Context, in *ReceiveSharedNoteRequest, opts ...grpc.CallOption) (*ReceiveSharedNoteResponse, error)
}

type noteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteServiceClient(cc grpc.ClientConnInterface) NoteServiceClient {
	return &noteServiceClient{cc}
}

func (c *noteServiceClient) GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error) {
	out := new(GetNoteResponse)
	err := c.cc.Invoke(ctx, NoteService_GetNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error) {
	out := new(ListNotesResponse)
	err := c.cc.Invoke(ctx, NoteService_ListNotes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error) {
	out := new(CreateNoteResponse)
	err := c.cc.Invoke(ctx, NoteService_CreateNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...grpc.CallOption) (*UpdateNoteResponse, error) {
	out := new(UpdateNoteResponse)
	err := c.cc.Invoke(ctx, NoteService_UpdateNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error) {
	out := new(DeleteNoteResponse)
	err := c.cc.Invoke(ctx, NoteService_DeleteNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) AppendEvent(ctx context.Context, in *AppendEventRequest, opts ...grpc.CallOption) (*AppendEventResponse, error) {
	out := new(AppendEventResponse)
	err := c.cc.Invoke(ctx, NoteService_AppendEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (NoteService_StreamEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &NoteService_ServiceDesc.Streams[0], NoteService_StreamEvents_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &noteServiceStreamEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NoteService_StreamEventsClient interface {
	Recv() (*StreamEventsResponse, error)
	grpc.ClientStream
}

type noteServiceStreamEventsClient struct {
	grpc.ClientStream
}

func (x *noteServiceStreamEventsClient) Recv() (*StreamEventsResponse, error) {
	m := new(StreamEventsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *noteServiceClient) SearchNotes(ctx context.Context, in *SearchNotesRequest, opts ...grpc.CallOption) (*SearchNotesResponse, error) {
	out := new(SearchNotesResponse)
	err := c.cc.Invoke(ctx, NoteService_SearchNotes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ReplaceContent(ctx context.Context, in *ReplaceContentRequest, opts ...grpc.CallOption) (*ReplaceContentResponse, error) {
	out := new(ReplaceContentResponse)
	err := c.cc.Invoke(ctx, NoteService_ReplaceContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ShareSecureNote(ctx context.Context, in *ShareSecureNoteRequest, opts ...grpc.CallOption) (*ShareSecureNoteResponse, error) {
	out := new(ShareSecureNoteResponse)
	err := c.cc.Invoke(ctx, NoteService_ShareSecureNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ReceiveSharedNote(ctx context.Context, in *ReceiveSharedNoteRequest, opts ...grpc.CallOption) (*ReceiveSharedNoteResponse, error) {
	out := new(ReceiveSharedNoteResponse)
	err := c.cc.Invoke(ctx, NoteService_ReceiveSharedNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteServiceServer is the server API for NoteService service.
// All implementations must embed UnimplementedNoteServiceServer
// for forward compatibility
type NoteServiceServer interface {
	// GetNote returns the full header + all events for a note.
	GetNote(context.Context, *GetNoteRequest) (*GetNoteResponse, error)
	// ListNotes returns all note headers visible to the caller.
	ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error)
	// CreateNote registers a new note (header only; events follow via AppendEvent).
	CreateNote(context.Context, *CreateNoteRequest) (*CreateNoteResponse, error)
	// UpdateNote mutates mutable metadata fields on a note using a FieldMask
	// for partial update semantics.
	UpdateNote(context.Context, *UpdateNoteRequest) (*UpdateNoteResponse, error)
	// DeleteNote soft-deletes a note by URN.
	DeleteNote(context.Context, *DeleteNoteRequest) (*DeleteNoteResponse, error)
	// AppendEvent appends a single event to an existing note.
	// For normal notes the server stores the plaintext entries and advances the
	// index. For secure notes it stores the encrypted blob verbatim.
	AppendEvent(context.Context, *AppendEventRequest) (*AppendEventResponse, error)
	// StreamEvents opens a server-side stream that pushes all events for a note
	// starting from a given sequence number. Used by clients to catch up after
	// reconnect. For secure note events the server streams the encrypted blob
	// without decrypting it.
	StreamEvents(*StreamEventsRequest, NoteService_StreamEventsServer) error
	// SearchNotes performs a server-side full-text search over normal note
	// content. Secure notes are never included in results.
	SearchNotes(context.Context, *SearchNotesRequest) (*SearchNotesResponse, error)
	// ReplaceContent atomically diffs the supplied plain-text content against the
	// note's current state and appends a single event capturing the delta.
	// Not permitted on secure notes.
	ReplaceContent(context.Context, *ReplaceContentRequest) (*ReplaceContentResponse, error)
	// ShareSecureNote merges per-device wrapped Content Encryption Keys into
	// every stored Event for the note without ever seeing the plaintext CEK.
	ShareSecureNote(context.Context, *ShareSecureNoteRequest) (*ShareSecureNoteResponse, error)
	// ReceiveSharedNote stores a note header and event stream forwarded from a
	// paired server. Idempotent: only events beyond the local head are written.
	ReceiveSharedNote(context.Context, *ReceiveSharedNoteRequest) (*ReceiveSharedNoteResponse, error)
	mustEmbedUnimplementedNoteServiceServer()
}

// UnimplementedNoteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNoteServiceServer struct {
}

func (UnimplementedNoteServiceServer) GetNote(context.Context, *GetNoteRequest) (*GetNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNote not implemented")
}
func (UnimplementedNoteServiceServer) ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotes not implemented")
}
func (UnimplementedNoteServiceServer) CreateNote(context.Context, *CreateNoteRequest) (*CreateNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNote not implemented")
}
func (UnimplementedNoteServiceServer) UpdateNote(context.Context, *UpdateNoteRequest) (*UpdateNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNote not implemented")
}
func (UnimplementedNoteServiceServer) DeleteNote(context.Context, *DeleteNoteRequest) (*DeleteNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNote not implemented")
}
func (UnimplementedNoteServiceServer) AppendEvent(context.Context, *AppendEventRequest) (*AppendEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEvent not implemented")
}
func (UnimplementedNoteServiceServer) StreamEvents(*StreamEventsRequest, NoteService_StreamEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedNoteServiceServer) SearchNotes(context.Context, *SearchNotesRequest) (*SearchNotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchNotes not implemented")
}
func (UnimplementedNoteServiceServer) ReplaceContent(context.Context, *ReplaceContentRequest) (*ReplaceContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceContent not implemented")
}
func (UnimplementedNoteServiceServer) ShareSecureNote(context.Context, *ShareSecureNoteRequest) (*ShareSecureNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShareSecureNote not implemented")
}
func (UnimplementedNoteServiceServer) ReceiveSharedNote(context.Context, *ReceiveSharedNoteRequest) (*ReceiveSharedNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveSharedNote not implemented")
}
func (UnimplementedNoteServiceServer) mustEmbedUnimplementedNoteServiceServer() {}

// UnsafeNoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteServiceServer will
// result in compilation errors.
type UnsafeNoteServiceServer interface {
	mustEmbedUnimplementedNoteServiceServer()
}

func RegisterNoteServiceServer(s grpc.ServiceRegistrar, srv NoteServiceServer) {
	s.RegisterService(&NoteService_ServiceDesc, srv)
}

func _NoteService_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_GetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).GetNote(ctx, req.(*GetNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ListNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ListNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ListNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ListNotes(ctx, req.(*ListNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_CreateNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).CreateNote(ctx, req.(*CreateNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_UpdateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).UpdateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_UpdateNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).UpdateNote(ctx, req.(*UpdateNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_DeleteNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).DeleteNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_DeleteNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).DeleteNote(ctx, req.(*DeleteNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_AppendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).AppendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_AppendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).AppendEvent(ctx, req.(*AppendEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NoteServiceServer).StreamEvents(m, &noteServiceStreamEventsServer{stream})
}

type NoteService_StreamEventsServer interface {
	Send(*StreamEventsResponse) error
	grpc.ServerStream
}

type noteServiceStreamEventsServer struct {
	grpc.ServerStream
}

func (x *noteServiceStreamEventsServer) Send(m *StreamEventsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NoteService_SearchNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).SearchNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_SearchNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).SearchNotes(ctx, req.(*SearchNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ReplaceContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ReplaceContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ReplaceContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ReplaceContent(ctx, req.(*ReplaceContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ShareSecureNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareSecureNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ShareSecureNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ShareSecureNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ShareSecureNote(ctx, req.(*ShareSecureNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ReceiveSharedNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveSharedNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ReceiveSharedNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ReceiveSharedNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ReceiveSharedNote(ctx, req.(*ReceiveSharedNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NoteService_ServiceDesc is the grpc.ServiceDesc for NoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notx.v1.NoteService",
	HandlerType: (*NoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNote",
			Handler:    _NoteService_GetNote_Handler,
		},
		{
			MethodName: "ListNotes",
			Handler:    _NoteService_ListNotes_Handler,
		},
		{
			MethodName: "CreateNote",
			Handler:    _NoteService_CreateNote_Handler,
		},
		{
			MethodName: "UpdateNote",
			Handler:    _NoteService_UpdateNote_Handler,
		},
		{
			MethodName: "DeleteNote",
			Handler:    _NoteService_DeleteNote_Handler,
		},
		{
			MethodName: "AppendEvent",
			Handler:    _NoteService_AppendEvent_Handler,
		},
		{
			MethodName: "SearchNotes",
			Handler:    _NoteService_SearchNotes_Handler,
		},
		{
			MethodName: "ReplaceContent",
			Handler:    _NoteService_ReplaceContent_Handler,
		},
		{
			MethodName: "ShareSecureNote",
			Handler:    _NoteService_ShareSecureNote_Handler,
		},
		{
			MethodName: "ReceiveSharedNote",
			Handler:    _NoteService_ReceiveSharedNote_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _NoteService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "note.proto",
}
