// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: server.proto

package notxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ServerPairingService_RegisterServer_FullMethodName      = "/notx.v1.ServerPairingService/RegisterServer"
	ServerPairingService_RenewCertificate_FullMethodName    = "/notx.v1.ServerPairingService/RenewCertificate"
	ServerPairingService_GetCACertificate_FullMethodName    = "/notx.v1.ServerPairingService/GetCACertificate"
	ServerPairingService_ListServers_FullMethodName         = "/notx.v1.ServerPairingService/ListServers"
	ServerPairingService_RevokeServer_FullMethodName        = "/notx.v1.ServerPairingService/RevokeServer"
	ServerPairingService_CreatePairingSecret_FullMethodName = "/notx.v1.ServerPairingService/CreatePairingSecret"
)

// ServerPairingServiceClient is the client API for ServerPairingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerPairingServiceClient interface {
	// RegisterServer registers a new peer server, issuing it a signed TLS
	// certificate from the local CA. The caller presents a CSR and a
	// short-lived pairing secret obtained via CreatePairingSecret.
	RegisterServer(ctx context.Context, in *RegisterServerRequest, opts ...grpc.CallOption) (*RegisterServerResponse, error)
	// RenewCertificate issues a fresh certificate for an already-registered
	// server before the current certificate expires.
	RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RenewCertificateResponse, error)
	// GetCACertificate returns the CA certificate in PEM form so that clients
	// can pin it for mTLS verification.
	GetCACertificate(ctx context.Context, in *GetCACertificateRequest, opts ...grpc.CallOption) (*GetCACertificateResponse, error)
	// ListServers returns all registered peer servers, optionally including
	// revoked entries.
	ListServers(ctx context.Context, in *ListServersRequest, opts ...grpc.CallOption) (*ListServersResponse, error)
	// RevokeServer revokes a peer server's certificate and marks it inactive.
	// Future connections from that server will be rejected.
	RevokeServer(ctx context.Context, in *RevokeServerRequest, opts ...grpc.CallOption) (*RevokeServerResponse, error)
	// CreatePairingSecret mints a short-lived secret token that a new peer
	// server can present in a RegisterServer call to authenticate itself.
	// The plaintext is returned exactly once and is not stored server-side.
	CreatePairingSecret(ctx context.Context, in *CreatePairingSecretRequest, opts ...grpc.CallOption) (*CreatePairingSecretResponse, error)
}

type serverPairingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServerPairingServiceClient(cc grpc.ClientConnInterface) ServerPairingServiceClient {
	return &serverPairingServiceClient{cc}
}

func (c *serverPairingServiceClient) RegisterServer(ctx context.Context, in *RegisterServerRequest, opts ...grpc.CallOption) (*RegisterServerResponse, error) {
	out := new(RegisterServerResponse)
	err := c.cc.Invoke(ctx, ServerPairingService_RegisterServer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverPairingServiceClient) RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RenewCertificateResponse, error) {
	out := new(RenewCertificateResponse)
	err := c.cc.Invoke(ctx, ServerPairingService_RenewCertificate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverPairingServiceClient) GetCACertificate(ctx context.Context, in *GetCACertificateRequest, opts ...grpc.CallOption) (*GetCACertificateResponse, error) {
	out := new(GetCACertificateResponse)
	err := c.cc.Invoke(ctx, ServerPairingService_GetCACertificate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverPairingServiceClient) ListServers(ctx context.Context, in *ListServersRequest, opts ...grpc.CallOption) (*ListServersResponse, error) {
	out := new(ListServersResponse)
	err := c.cc.Invoke(ctx, ServerPairingService_ListServers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverPairingServiceClient) RevokeServer(ctx context.Context, in *RevokeServerRequest, opts ...grpc.CallOption) (*RevokeServerResponse, error) {
	out := new(RevokeServerResponse)
	err := c.cc.Invoke(ctx, ServerPairingService_RevokeServer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverPairingServiceClient) CreatePairingSecret(ctx context.Context, in *CreatePairingSecretRequest, opts ...grpc.CallOption) (*CreatePairingSecretResponse, error) {
	out := new(CreatePairingSecretResponse)
	err := c.cc.Invoke(ctx, ServerPairingService_CreatePairingSecret_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerPairingServiceServer is the server API for ServerPairingService service.
// All implementations must embed UnimplementedServerPairingServiceServer
// for forward compatibility
type ServerPairingServiceServer interface {
	// RegisterServer registers a new peer server, issuing it a signed TLS
	// certificate from the local CA. The caller presents a CSR and a
	// short-lived pairing secret obtained via CreatePairingSecret.
	RegisterServer(context.Context, *RegisterServerRequest) (*RegisterServerResponse, error)
	// RenewCertificate issues a fresh certificate for an already-registered
	// server before the current certificate expires.
	RenewCertificate(context.Context, *RenewCertificateRequest) (*RenewCertificateResponse, error)
	// GetCACertificate returns the CA certificate in PEM form so that clients
	// can pin it for mTLS verification.
	GetCACertificate(context.Context, *GetCACertificateRequest) (*GetCACertificateResponse, error)
	// ListServers returns all registered peer servers, optionally including
	// revoked entries.
	ListServers(context.Context, *ListServersRequest) (*ListServersResponse, error)
	// RevokeServer revokes a peer server's certificate and marks it inactive.
	// Future connections from that server will be rejected.
	RevokeServer(context.Context, *RevokeServerRequest) (*RevokeServerResponse, error)
	// CreatePairingSecret mints a short-lived secret token that a new peer
	// server can present in a RegisterServer call to authenticate itself.
	// The plaintext is returned exactly once and is not stored server-side.
	CreatePairingSecret(context.Context, *CreatePairingSecretRequest) (*CreatePairingSecretResponse, error)
	mustEmbedUnimplementedServerPairingServiceServer()
}

// UnimplementedServerPairingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServerPairingServiceServer struct {
}

func (UnimplementedServerPairingServiceServer) RegisterServer(context.Context, *RegisterServerRequest) (*RegisterServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterServer not implemented")
}
func (UnimplementedServerPairingServiceServer) RenewCertificate(context.Context, *RenewCertificateRequest) (*RenewCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewCertificate not implemented")
}
func (UnimplementedServerPairingServiceServer) GetCACertificate(context.Context, *GetCACertificateRequest) (*GetCACertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCACertificate not implemented")
}
func (UnimplementedServerPairingServiceServer) ListServers(context.Context, *ListServersRequest) (*ListServersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServers not implemented")
}
func (UnimplementedServerPairingServiceServer) RevokeServer(context.Context, *RevokeServerRequest) (*RevokeServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeServer not implemented")
}
func (UnimplementedServerPairingServiceServer) CreatePairingSecret(context.Context, *CreatePairingSecretRequest) (*CreatePairingSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePairingSecret not implemented")
}
func (UnimplementedServerPairingServiceServer) mustEmbedUnimplementedServerPairingServiceServer() {}

// UnsafeServerPairingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerPairingServiceServer will
// result in compilation errors.
type UnsafeServerPairingServiceServer interface {
	mustEmbedUnimplementedServerPairingServiceServer()
}

func RegisterServerPairingServiceServer(s grpc.ServiceRegistrar, srv ServerPairingServiceServer) {
	s.RegisterService(&ServerPairingService_ServiceDesc, srv)
}

func _ServerPairingService_RegisterServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerPairingServiceServer).RegisterServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerPairingService_RegisterServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerPairingServiceServer).RegisterServer(ctx, req.(*RegisterServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerPairingService_RenewCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerPairingServiceServer).RenewCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerPairingService_RenewCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerPairingServiceServer).RenewCertificate(ctx, req.(*RenewCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerPairingService_GetCACertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCACertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerPairingServiceServer).GetCACertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerPairingService_GetCACertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerPairingServiceServer).GetCACertificate(ctx, req.(*GetCACertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerPairingService_ListServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerPairingServiceServer).ListServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerPairingService_ListServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerPairingServiceServer).ListServers(ctx, req.(*ListServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerPairingService_RevokeServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerPairingServiceServer).RevokeServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerPairingService_RevokeServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerPairingServiceServer).RevokeServer(ctx, req.(*RevokeServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerPairingService_CreatePairingSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePairingSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerPairingServiceServer).CreatePairingSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerPairingService_CreatePairingSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerPairingServiceServer).CreatePairingSecret(ctx, req.(*CreatePairingSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerPairingService_ServiceDesc is the grpc.ServiceDesc for ServerPairingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerPairingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notx.v1.ServerPairingService",
	HandlerType: (*ServerPairingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterServer",
			Handler:    _ServerPairingService_RegisterServer_Handler,
		},
		{
			MethodName: "RenewCertificate",
			Handler:    _ServerPairingService_RenewCertificate_Handler,
		},
		{
			MethodName: "GetCACertificate",
			Handler:    _ServerPairingService_GetCACertificate_Handler,
		},
		{
			MethodName: "ListServers",
			Handler:    _ServerPairingService_ListServers_Handler,
		},
		{
			MethodName: "RevokeServer",
			Handler:    _ServerPairingService_RevokeServer_Handler,
		},
		{
			MethodName: "CreatePairingSecret",
			Handler:    _ServerPairingService_CreatePairingSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
