// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: sync.proto

package notxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SyncService_SyncNotes_FullMethodName = "/notx.v1.SyncService/SyncNotes"
)

// SyncServiceClient is the client API for SyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncServiceClient interface {
	// SyncNotes is a bidirectional streaming RPC.
	// The caller (local server) sends SyncNoteMessage frames — one per local note.
	// The server (cloud) responds with SyncNoteResult frames — one per received note,
	// plus additional SyncNoteMessage frames for notes that exist only on the cloud.
	SyncNotes(ctx context.Context, opts ...grpc.CallOption) (SyncService_SyncNotesClient, error)
}

type syncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncServiceClient(cc grpc.ClientConnInterface) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) SyncNotes(ctx context.Context, opts ...grpc.CallOption) (SyncService_SyncNotesClient, error) {
	stream, err := c.cc.NewStream(ctx, &SyncService_ServiceDesc.Streams[0], SyncService_SyncNotes_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &syncServiceSyncNotesClient{stream}
	return x, nil
}

type SyncService_SyncNotesClient interface {
	Send(*SyncNoteMessage) error
	Recv() (*SyncNoteResult, error)
	grpc.ClientStream
}

type syncServiceSyncNotesClient struct {
	grpc.ClientStream
}

func (x *syncServiceSyncNotesClient) Send(m *SyncNoteMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *syncServiceSyncNotesClient) Recv() (*SyncNoteResult, error) {
	m := new(SyncNoteResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SyncServiceServer is the server API for SyncService service.
// All implementations must embed UnimplementedSyncServiceServer
// for forward compatibility
type SyncServiceServer interface {
	// SyncNotes is a bidirectional streaming RPC.
	// The caller (local server) sends SyncNoteMessage frames — one per local note.
	// The server (cloud) responds with SyncNoteResult frames — one per received note,
	// plus additional SyncNoteMessage frames for notes that exist only on the cloud.
	SyncNotes(SyncService_SyncNotesServer) error
	mustEmbedUnimplementedSyncServiceServer()
}

// UnimplementedSyncServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSyncServiceServer struct {
}

func (UnimplementedSyncServiceServer) SyncNotes(SyncService_SyncNotesServer) error {
	return status.Errorf(codes.Unimplemented, "method SyncNotes not implemented")
}
func (UnimplementedSyncServiceServer) mustEmbedUnimplementedSyncServiceServer() {}

// UnsafeSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncServiceServer will
// result in compilation errors.
type UnsafeSyncServiceServer interface {
	mustEmbedUnimplementedSyncServiceServer()
}

func RegisterSyncServiceServer(s grpc.ServiceRegistrar, srv SyncServiceServer) {
	s.RegisterService(&SyncService_ServiceDesc, srv)
}

func _SyncService_SyncNotes_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncServiceServer).SyncNotes(&syncServiceSyncNotesServer{stream})
}

type SyncService_SyncNotesServer interface {
	Send(*SyncNoteResult) error
	Recv() (*SyncNoteMessage, error)
	grpc.ServerStream
}

type syncServiceSyncNotesServer struct {
	grpc.ServerStream
}

func (x *syncServiceSyncNotesServer) Send(m *SyncNoteResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *syncServiceSyncNotesServer) Recv() (*SyncNoteMessage, error) {
	m := new(SyncNoteMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SyncService_ServiceDesc is the grpc.ServiceDesc for SyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notx.v1.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncNotes",
			Handler:       _SyncService_SyncNotes_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sync.proto",
}
