// Code generated by protoc-gen-go. DO NOT EDIT.
// Manually extended to add SyncStreamMessage, NoteChangedNotif, SyncPullRequest, SyncPing.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: sync.proto

package notxpb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncNoteMessage carries a note header and its complete event stream.
// Sent by the local server for each note it wants to push/sync.
type SyncNoteMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *NoteHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Events []*Event    `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *SyncNoteMessage) Reset() {
	*x = SyncNoteMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncNoteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncNoteMessage) ProtoMessage() {}

func (x *SyncNoteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncNoteMessage.ProtoReflect.Descriptor instead.
func (*SyncNoteMessage) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncNoteMessage) GetHeader() *NoteHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SyncNoteMessage) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// SyncNoteResult is sent by the cloud server for each note it processed.
type SyncNoteResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteUrn      string `protobuf:"bytes,1,opt,name=note_urn,json=noteUrn,proto3" json:"note_urn,omitempty"`
	EventsStored int32  `protobuf:"varint,2,opt,name=events_stored,json=eventsStored,proto3" json:"events_stored,omitempty"`
	Error        string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // non-empty on per-note error (does not close the stream)
}

func (x *SyncNoteResult) Reset() {
	*x = SyncNoteResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncNoteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncNoteResult) ProtoMessage() {}

func (x *SyncNoteResult) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncNoteResult.ProtoReflect.Descriptor instead.
func (*SyncNoteResult) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncNoteResult) GetNoteUrn() string {
	if x != nil {
		return x.NoteUrn
	}
	return ""
}

func (x *SyncNoteResult) GetEventsStored() int32 {
	if x != nil {
		return x.EventsStored
	}
	return 0
}

func (x *SyncNoteResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SyncStreamMessage is the envelope for the long-lived SyncStream RPC.
// Exactly one of the payload fields is non-nil per message.
type SyncStreamMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Exactly one of these is non-nil.
	NotePush    *SyncNoteMessage  `protobuf:"bytes,1,opt,name=note_push,json=notePush,proto3,oneof" json:"note_push,omitempty"`
	PushAck     *SyncNoteResult   `protobuf:"bytes,2,opt,name=push_ack,json=pushAck,proto3,oneof" json:"push_ack,omitempty"`
	NoteChanged *NoteChangedNotif `protobuf:"bytes,3,opt,name=note_changed,json=noteChanged,proto3,oneof" json:"note_changed,omitempty"`
	PullRequest *SyncPullRequest  `protobuf:"bytes,4,opt,name=pull_request,json=pullRequest,proto3,oneof" json:"pull_request,omitempty"`
	Ping        *SyncPing         `protobuf:"bytes,5,opt,name=ping,proto3,oneof" json:"ping,omitempty"`
}

func (x *SyncStreamMessage) Reset()         { *x = SyncStreamMessage{} }
func (x *SyncStreamMessage) String() string { return protoimpl.X.MessageStringOf(x) }
func (*SyncStreamMessage) ProtoMessage()    {}

func (x *SyncStreamMessage) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *SyncStreamMessage) GetNotePush() *SyncNoteMessage {
	if x != nil {
		return x.NotePush
	}
	return nil
}

func (x *SyncStreamMessage) GetPushAck() *SyncNoteResult {
	if x != nil {
		return x.PushAck
	}
	return nil
}

func (x *SyncStreamMessage) GetNoteChanged() *NoteChangedNotif {
	if x != nil {
		return x.NoteChanged
	}
	return nil
}

func (x *SyncStreamMessage) GetPullRequest() *SyncPullRequest {
	if x != nil {
		return x.PullRequest
	}
	return nil
}

func (x *SyncStreamMessage) GetPing() *SyncPing {
	if x != nil {
		return x.Ping
	}
	return nil
}

// NoteChangedNotif is pushed by the cloud to inform the local server that
// a note has been updated on the cloud side.
type NoteChangedNotif struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteUrn   string                 `protobuf:"bytes,1,opt,name=note_urn,json=noteUrn,proto3" json:"note_urn,omitempty"`
	HeadSeq   int32                  `protobuf:"varint,2,opt,name=head_seq,json=headSeq,proto3" json:"head_seq,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *NoteChangedNotif) Reset()         { *x = NoteChangedNotif{} }
func (x *NoteChangedNotif) String() string { return protoimpl.X.MessageStringOf(x) }
func (*NoteChangedNotif) ProtoMessage()    {}

func (x *NoteChangedNotif) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *NoteChangedNotif) GetNoteUrn() string {
	if x != nil {
		return x.NoteUrn
	}
	return ""
}

func (x *NoteChangedNotif) GetHeadSeq() int32 {
	if x != nil {
		return x.HeadSeq
	}
	return 0
}

func (x *NoteChangedNotif) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// SyncPullRequest asks the cloud to send the note's events from from_seq onward.
type SyncPullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteUrn string `protobuf:"bytes,1,opt,name=note_urn,json=noteUrn,proto3" json:"note_urn,omitempty"`
	FromSeq int32  `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
}

func (x *SyncPullRequest) Reset()         { *x = SyncPullRequest{} }
func (x *SyncPullRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*SyncPullRequest) ProtoMessage()    {}

func (x *SyncPullRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *SyncPullRequest) GetNoteUrn() string {
	if x != nil {
		return x.NoteUrn
	}
	return ""
}

func (x *SyncPullRequest) GetFromSeq() int32 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

// SyncPing is a keepalive message. The receiver should respond with another SyncPing.
type SyncPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimestampMs int64 `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
}

func (x *SyncPing) Reset()         { *x = SyncPing{} }
func (x *SyncPing) String() string { return protoimpl.X.MessageStringOf(x) }
func (*SyncPing) ProtoMessage()    {}

func (x *SyncPing) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *SyncPing) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_sync_proto protoreflect.FileDescriptor

var file_sync_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6e, 0x6f,
	0x74, 0x78, 0x2e, 0x76, 0x31, 0x1a, 0x0a, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x66, 0x0a, 0x0f, 0x53, 0x79, 0x6e, 0x63, 0x4e, 0x6f, 0x74, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4e,
	0x6f, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x26, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x66, 0x0a, 0x0e, 0x53, 0x79, 0x6e,
	0x63, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e,
	0x6f, 0x74, 0x65, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e,
	0x6f, 0x74, 0x65, 0x55, 0x72, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x32, 0x51, 0x0a, 0x0b, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x42, 0x0a, 0x09, 0x53, 0x79, 0x6e, 0x63, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x18, 0x2e,
	0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x4e, 0x6f, 0x74, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x17, 0x2e, 0x6e, 0x6f, 0x74, 0x78, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x7a, 0x65, 0x62, 0x61, 0x71, 0x75, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x78, 0x2d,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6e, 0x6f, 0x74,
	0x78, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData = file_sync_proto_rawDesc
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(file_sync_proto_rawDescData)
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sync_proto_goTypes = []interface{}{
	(*SyncNoteMessage)(nil), // 0: notx.v1.SyncNoteMessage
	(*SyncNoteResult)(nil),  // 1: notx.v1.SyncNoteResult
	(*NoteHeader)(nil),      // 2: notx.v1.NoteHeader
	(*Event)(nil),           // 3: notx.v1.Event
}
var file_sync_proto_depIdxs = []int32{
	2, // 0: notx.v1.SyncNoteMessage.header:type_name -> notx.v1.NoteHeader
	3, // 1: notx.v1.SyncNoteMessage.events:type_name -> notx.v1.Event
	0, // 2: notx.v1.SyncService.SyncNotes:input_type -> notx.v1.SyncNoteMessage
	1, // 3: notx.v1.SyncService.SyncNotes:output_type -> notx.v1.SyncNoteResult
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	file_note_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncNoteMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncNoteResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_rawDesc = nil
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
